### ISSUE TITLE
Nullpointer exception with !type:[subtype]

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#397]
Exception in GROOVE java.lang.NullPointerException
	at java.util.HashSet.<init>(HashSet.java:116)
	at groove.grammar.rule.RuleEdge.<init>(RuleEdge.java:63)
	at groove.grammar.rule.RuleFactory.createEdge(RuleFactory.java:83)
	at groove.match.plan.PlanSearchEngine$PlanData.createEdgeSearchItem(PlanSearchEngine.java:437)...

Reported by: snatch7

**Comment by rensink** [comment]
Thanks, it's exactly what I wanted. Works like a charm.

Original comment by: snatch7
