### ISSUE TITLE
NullPointerException in layout

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#398]
When doing:

$ java -jar bin/Generator.jar -o file ./test.gps start

I get:

Grammar:	./test.gps
Start graph:	[start]
Exploration:	bfs / final / infinite
Timestamp:	Sun Apr 21 10:19:47 CEST 2013

Progress:	

Statistics:

	States:			2
	Transitions:	1

Time (ms):	201
	Matching:			5	 2.5%
	Transforming:		163	81.1%
	Iso checking:		13	 6.5%
	Building GTS:		11	 5.5%
	Measuring:			0	 0.0%
	Initialization:		9	 4.5%

Space (kB):	641

java.lang.NullPointerException
	at groove.io.xml.AbstractJaxbGxlIO.layout(AbstractJaxbGxlIO.java:125)
	at groove.io.xml.AbstractJaxbGxlIO.graphToGxl(AbstractJaxbGxlIO.java:200)
	at groove.io.xml.AbstractJaxbGxlIO.saveGraph(AbstractJaxbGxlIO.java:81)
	at groove.io.xml.AbstractGxl.marshalAnyGraph(AbstractGxl.java:131)
	at groove.util.Groove.saveGraph(Groove.java:137)
	at groove.explore.Generator.exportSimulation(Generator.java:472)
	at groove.explore.Generator.report(Generator.java:541)
	at groove.explore.Generator.start(Generator.java:170)
	at groove.explore.Generator.generate(Generator.java:118)
	at groove.explore.Generator.main(Generator.java:107)
	at groove.Generator.main(Generator.java:31)

Reported by: vincentdebruijn

**Comment by rensink** [comment]
old version, nvm

Original comment by: vincentdebruijn

**Comment by rensink** [comment]
- **status**: open --> closed-out-of-date
- **assigned_to**: Arend Rensink


Original comment by: rensink
