### ISSUE TITLE
NullPointerException after Ctrl-Z

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#400]
Steps before GROOVE crash:
- I was editing a rule by copying a part of another rule to it.
- When copied, the rule I was working in was inconsistent (loose int: nodes pointing to forall: nodes etc.).
- I accidentally moved another element (an @ label from an edge) in my rule and tried to undo that by pressing CTRL-Z.
- After that, the program crashed.

Stacktrace:

Exception in GROOVE java.lang.NullPointerException
	at org.jgraph.graph.EdgeView$EdgeHandle.reloadPoints(Unknown Source)
	at org.jgraph.graph.EdgeView$EdgeHandle.<init>(Unknown Source)
	at groove.gui.jgraph.JEdgeView$MyEdgeHandle.<init>(JEdgeView.java:410)
	at groove.gui.jgraph.JEdgeView.getHandle(JEdgeView.java:166)
	at org.jgraph.plaf.basic.BasicGraphUI$RootHandle.<init>(Unknown Source)
	at org.jgraph.plaf.basic.BasicGraphUI.createHandle(Unknown Source)
	at org.jgraph.plaf.basic.BasicGraphUI.updateHandle(Unknown Source)
	at org.jgraph.plaf.basic.BasicGraphUI.updateSize(Unknown Source)
	at org.jgraph.plaf.basic.BasicGraphUI$GraphLayoutCacheHandler.graphLayoutCacheChanged(Unknown Source)
	at org.jgraph.graph.GraphLayoutCache.fireGraphLayoutCacheChanged(Unknown Source)
	at org.jgraph.graph.GraphLayoutCache$GraphLayoutCacheEdit.execute(Unknown Source)
	at org.jgraph.graph.GraphLayoutCache$GraphLayoutCacheEdit.undo(Unknown Source)
	at javax.swing.undo.CompoundEdit.undo(Unknown Source)
	at org.jgraph.graph.DefaultGraphModel$GraphModelEdit.undo(Unknown Source)
	at javax.swing.undo.UndoManager.undoTo(Unknown Source)
	at javax.swing.undo.UndoManager.undo(Unknown Source)
	at groove.gui.display.GraphEditorTab.undoLastEdit(GraphEditorTab.java:765)
	at groove.gui.display.GraphEditorTab.access$14(GraphEditorTab.java:763)
	at groove.gui.display.GraphEditorTab$11.actionPerformed(GraphEditorTab.java:911)
	at javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at javax.swing.JComponent.processKeyBinding(Unknown Source)
	at javax.swing.JComponent.processKeyBindings(Unknown Source)
	at javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Reported by: dylan202

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
I fixed a bug in the undo behaviour, but I'm not quite sure it's the same one :-( In any case, I couldn't reproduce this afterwards. --Arend


Original comment by: rensink
