### ISSUE TITLE
NPE on grammar creation

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#409]
The current SVN version of the Simulator crashes with the following NPE when you finish creating a grammar using 'File -> New Grammar ...'

Exception in GROOVE java.lang.NullPointerException
	at groove.grammar.model.GrammarModel.getId(GrammarModel.java:94)
	at groove.gui.Simulator.setTitle(Simulator.java:828)
	at groove.gui.Simulator.update(Simulator.java:161)
	at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1173)
	at groove.gui.SimulatorModel.finish(SimulatorModel.java:1139)
	at groove.gui.SimulatorModel.setGrammar(SimulatorModel.java:771)
	at groove.gui.SimulatorModel.doNewGrammar(SimulatorModel.java:352)
	at groove.gui.action.NewGrammarAction.execute(NewGrammarAction.java:52)
	at groove.gui.action.SimulatorAction.actionPerformed(SimulatorAction.java:232)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
	[...]

Reported by: zambon

**Comment by rensink** [comment]
Stupid, stupid. Fixed in the HEAD

Original comment by: rensink
