### ISSUE TITLE
InterruptedException in Generator due to System.exit

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#422]
On short jobs, the Generator has a deamon thread "ImageFetcher" that is not done upon completion of the process, and when forced to shut down by System.exit(0) throws an InterruptedException:

Exception while removing reference: java.lang.InterruptedException
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at sun.java2d.Disposer.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I think the ImageFetcher should not kick in at all, since this is a non-GUI application, but this probably happens upon class loading of some class with static (icon?) fields. Find out which class, and maybe introduce more laziness?

Reported by: rensink

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
I think it's probably fixed; I haven't been able to reproduce the problem in 20 tries where before it occurred every 2nd time. 

Trick: add a class load breakpoint for ImageFetcher, to detect at what point and for what cause it is started up.

Original comment by: rensink
