### ISSUE TITLE
Simulator crashes with NPE after BFS exploration.

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#427]
The attached grammar crashes the Simulator after a BFS exploration is finished and is being rendered. The crash doesn't happend when DFS is used (smaller state space??)

Stack trace:
Exception in GROOVE java.lang.NullPointerException
	at groove.gui.jgraph.LTSJModel.statusUpdate(LTSJModel.java:102)
	at groove.lts.GTS.fireUpdateState(GTS.java:503)
	at groove.lts.AbstractGraphState.fireStatus(AbstractGraphState.java:307)
	at groove.lts.AbstractGraphState.setClosed(AbstractGraphState.java:208)
	at groove.lts.StateMatches.trySchedule(StateMatches.java:124)
	at groove.lts.StateMatches.getAll(StateMatches.java:64)
	at groove.lts.AbstractGraphState.getMatches(AbstractGraphState.java:168)
	at groove.gui.tree.StateTree.createStateNode(StateTree.java:320)
	at groove.gui.tree.StateTree.fill(StateTree.java:288)
	at groove.gui.tree.StateTree.getStateNode(StateTree.java:395)
	at groove.gui.tree.StateTree.refreshSelection(StateTree.java:350)
	at groove.gui.tree.StateTree.update(StateTree.java:222)
	at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1153)
	at groove.gui.SimulatorModel.finish(SimulatorModel.java:1120)
	at groove.gui.SimulatorModel.setState(SimulatorModel.java:591)
	at groove.gui.action.ExploreAction.explore(ExploreAction.java:108)
	at groove.gui.action.ExploreAction.execute(ExploreAction.java:61)
	at groove.gui.action.SimulatorAction.actionPerformed(SimulatorAction.java:231)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
[...]

Reported by: zambon

**Comment by rensink** [comment]
- **status**: open --> closed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
Very curious that this hasn't shown up long before. I think this kicks in whenever a final state (without applicable rules) is found for a state that isn't rendered (because its number exceeds the bound set in the simulator).


Original comment by: rensink
