### ISSUE TITLE
Error in manually exploring sample grammar

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#433]
Do full exploration with displayed state bound set to 100, then manually select successor of state selected after exploration (s1667 in my instance).

Exception in thread "AWT-EventQueue-0" java.lang.AssertionError: Event error for fresh() applied to Nodes: [jint:3, jint:2, jint:1, n2, n0, jint:0, n6, n4, n3, n1, n5]; Edges: [n3--next-->n1, n0--next-->n2, n0--next-->n3, n6--eyes-->jint:3, n4--on-->n2, n5--on-->n3, n5--turn-->n5, n1--next-->n2, n4--blue-->n4, n2--next-->n3, n6--eyes-->jint:2, n6--eyes-->jint:1, n1--next-->n0, n5--red-->n5, n2--next-->n1, n3--next-->n0, n6--throw-->jint:0, n5--owns-->n3]
	at groove.transform.RuleApplication.<init>(RuleApplication.java:77)
	at groove.transform.RuleApplication.<init>(RuleApplication.java:59)
	at groove.transform.AbstractRuleEvent.newApplication(AbstractRuleEvent.java:68)
	at groove.lts.RecipeTransition.computeMorphism(RecipeTransition.java:295)
	at groove.lts.RecipeTransition.getMorphism(RecipeTransition.java:266)
	at groove.gui.display.StateDisplay.transferAttributes(StateDisplay.java:516)
	at groove.gui.display.StateDisplay.setNextStateLayout(StateDisplay.java:482)
	at groove.gui.display.StateDisplay.getAspectJModel(StateDisplay.java:460)
	at groove.gui.display.StateDisplay.displayState(StateDisplay.java:405)
	at groove.gui.display.StateDisplay.update(StateDisplay.java:316)
	at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1183)
	at groove.gui.SimulatorModel.finish(SimulatorModel.java:1150)
	at groove.gui.SimulatorModel.setState(SimulatorModel.java:603)
	at groove.gui.display.LTSDisplay$MyMouseListener.mouseClicked(LTSDisplay.java:656)
	at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$000(Unknown Source)
	at java.awt.EventQueue$1.run(Unknown Source)
	at java.awt.EventQueue$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$2.run(Unknown Source)
	at java.awt.EventQueue$2.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Reported by: rensink

**Comment by rensink** [comment]
- **status**: open --> closed-fixed


Original comment by: rensink
