### ISSUE TITLE
NPE when saving a control program with empty recipe

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#439]
When I save a control program or open a gps with a control program that contains a recipe declaration like "recipe x() {}" it crashes with a NPE:

Exception in GROOVE java.lang.NullPointerException
	at groove.grammar.Recipe.getRules(Recipe.java:49)
	at groove.grammar.model.CompositeControlModel.getRuleRecipeMap(CompositeControlModel.java:117)
	at groove.grammar.model.CompositeControlModel.getRecipes(CompositeControlModel.java:105)
	at groove.grammar.model.RuleModel.getRecipes(RuleModel.java:134)
	at groove.grammar.model.RuleModel.hasRecipes(RuleModel.java:139)
	at groove.gui.action.EnableAction.refresh(EnableAction.java:56)
	at groove.gui.action.ActionStore.refreshActions(ActionStore.java:81)
	at groove.gui.action.ActionStore.update(ActionStore.java:59)
	at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1166)
	at groove.gui.SimulatorModel.finish(SimulatorModel.java:1133)
	at groove.gui.SimulatorModel.doAddText(SimulatorModel.java:256)
	at groove.gui.action.SaveAction.doSaveText(SaveAction.java:143)
	at groove.gui.action.SaveAction.execute(SaveAction.java:75)
	at groove.gui.action.SimulatorAction.actionPerformed(SimulatorAction.java:231)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1662)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2869)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2930)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
	at java.awt.Component.processEvent(Component.java:6293)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
	at java.awt.Component.dispatchEventImpl(Component.java:4742)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Reported by: cmur2

**Comment by rensink** [comment]
I believe this issue was fixed in the latest SVN revision, since I can't reproduce the bug. Just to make sure, could you provide (attach) the grammar that is causing the problem for testing?

Original comment by: zambon

**Comment by rensink** [comment]
Yup. It works in the current revision. (Works in the sense that you get a proper error message instead of a NPE.)
I'll make a new bugfix release.

Original comment by: zambon

**Comment by rensink** [comment]
Thank you, it's very annoying when you accidentally run into this situation.

Original comment by: cmur2

**Comment by rensink** [comment]
Yes, it certainly is. Sorry about that. We hope you understand that it is quite challenging to get rid of all bugs in the code, especially since Groove is a research tool and new features are being added all the time.
We try to compensate this with a fast turnaround time when someone shows up with a problem. BTW, the new release is already available for download.

Original comment by: zambon

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Eduardo Zambon


Original comment by: zambon
