### ISSUE TITLE
NPE in when saving/opening a control program

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#440]
Saving/opening the attached grammar causes an NPE with the following stack trace:

Exception in GROOVE java.lang.NullPointerException
	at groove.control.parse.CtrlHelper.createArgs(CtrlHelper.java:551)
	at groove.control.parse.CtrlHelper.checkGroupCall(CtrlHelper.java:451)
	at groove.control.parse.CtrlChecker.rule(CtrlChecker.java:2167)
	at groove.control.parse.CtrlChecker.stat(CtrlChecker.java:1977)
	at groove.control.parse.CtrlChecker.stat(CtrlChecker.java:1521)
	at groove.control.parse.CtrlChecker.block(CtrlChecker.java:1228)
	at groove.control.parse.CtrlChecker.program(CtrlChecker.java:233)
	at groove.control.parse.CtrlTree.check(CtrlTree.java:421)
	at groove.grammar.model.ControlModel.compute(ControlModel.java:57)
	at groove.grammar.model.ControlModel.compute(ControlModel.java:1)
	at groove.grammar.model.ResourceModel.synchronise(ResourceModel.java:170)
	at groove.grammar.model.ResourceModel.toResource(ResourceModel.java:129)
	at groove.gui.action.PreviewControlAction.getTemplates(PreviewControlAction.java:107)
	at groove.gui.action.PreviewControlAction.refresh(PreviewControlAction.java:84)
	at groove.gui.action.ActionStore.refreshActions(ActionStore.java:81)
	at groove.gui.action.ActionStore.update(ActionStore.java:59)
[...]

Reported by: zambon

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Eduardo Zambon


Original comment by: zambon
