### ISSUE TITLE
ArrayOutOfBoundsException in control

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#441]
Exploring the attached grammar causes the following exception:

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at groove.control.Valuator.get(Valuator.java:46)
	at groove.lts.RecipeTransition.getArguments(RecipeTransition.java:242)
	at groove.lts.RuleTransitionLabel.computeParameters(RuleTransitionLabel.java:220)
	at groove.lts.RecipeTransition.computeLine(RecipeTransition.java:346)
	at groove.graph.ALabelEdge.toLine(ALabelEdge.java:47)
	at groove.graph.ALabelEdge.text(ALabelEdge.java:41)
	at groove.gui.tree.LabelFilter$LabelEntry.hashCode(LabelFilter.java:362)
[...]

Reported by: zambon

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Eduardo Zambon


Original comment by: zambon
