### ISSUE TITLE
Uncaught exception - Applying hierarchical layout

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#443]
I played around with different layouts and when I applied the hierarchical layout, I got an uncaught exception with the following trace:

Exception in GROOVE java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:714)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:451)
	at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:392)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:191)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:146)
	at java.util.Arrays.sort(Arrays.java:472)
	at com.jgraph.layout.hierarchical.JGraphCoordinateAssignment.rankMedianPosition(Unknown Source)
	at com.jgraph.layout.hierarchical.JGraphCoordinateAssignment.medianPos(Unknown Source)
	at com.jgraph.layout.hierarchical.JGraphCoordinateAssignment.run(Unknown Source)
	at com.jgraph.layout.hierarchical.JGraphHierarchicalLayout.run(Unknown Source)
	at groove.gui.layout.LayouterItem.run(LayouterItem.java:98)
	at groove.gui.layout.LayouterItem.start(LayouterItem.java:77)
	at groove.gui.action.LayoutAction.doLayout(LayoutAction.java:62)
	at groove.gui.action.LayoutAction.actionPerformed(LayoutAction.java:46)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6505)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Reported by: sjunges

**Comment by rensink** [comment]
I updated to the last version (5.2.2), got the same error. Repost the stack trace in case lines have changed.

Exception in GROOVE java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:714)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:451)
	at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:392)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:191)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:146)
	at java.util.Arrays.sort(Arrays.java:472)
	at com.jgraph.layout.hierarchical.JGraphCoordinateAssignment.rankMedianPosition(Unknown Source)
	at com.jgraph.layout.hierarchical.JGraphCoordinateAssignment.medianPos(Unknown Source)
	at com.jgraph.layout.hierarchical.JGraphCoordinateAssignment.run(Unknown Source)
	at com.jgraph.layout.hierarchical.JGraphHierarchicalLayout.run(Unknown Source)
	at groove.gui.layout.LayouterItem.run(LayouterItem.java:95)
	at groove.gui.layout.LayouterItem.start(LayouterItem.java:74)
	at groove.gui.action.LayoutAction.doLayout(LayoutAction.java:62)
	at groove.gui.action.LayoutAction.actionPerformed(LayoutAction.java:46)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6505)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)


Original comment by: sjunges

**Comment by rensink** [comment]
- **assigned_to**: Eduardo Zambon


Original comment by: zambon

**Comment by rensink** [comment]
I played around with several grammars I had around but I couldn't trigger this bug...
Could you please provide your grammar along with the sequence of steps to reproduce it?
Thanks.

Original comment by: zambon

**Comment by rensink** [comment]
I'm currently not able to reproduce the bug. It occured after playing around with different rules and then doing a linear search on the lts. When I tried to examine the resulting state, and I tried to apply the hierarchical layout (which I used succesfully before). 

If I happen to stumble upon a reproducable case, I will share it here :) 

Original comment by: sjunges

**Comment by rensink** [comment]
This is only a guess but from what I could infer from the stack trace this seems to be some incompatibility between the jGraph library that we use and some java.util structures. The library is a bit old and maybe the latest Java 7 implementation broke something...

To be honest, I would hardly know where to start to try and fix this, since there is hardly any "proper" Groove code involved.

I'll close this ticket for now. Please re-open it if you see the need.

Original comment by: zambon

**Comment by rensink** [comment]
- **status**: open --> closed-works-for-me


Original comment by: zambon
