### ISSUE TITLE
Bug during rule application

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#445]
After (manually) applying various rules (state 99), Groove crashed.

I did not manage to reproduce as I did not remember the 99 steps I applied :)
I will save more intermediate steps in the hope to find a reproducable path.
Meanwhile, I post the trace here, just in case I will stumble again over the same issue :)

Exception in GROOVE java.lang.ClassCastException: groove.gui.tree.StateTree$StateTreeNode cannot be cast to groove.gui.tree.StateTree$RangeTreeNode
	at groove.gui.tree.StateTree.getStateNode(StateTree.java:482)
	at groove.gui.tree.StateTree.refreshSelection(StateTree.java:425)
	at groove.gui.tree.StateTree.update(StateTree.java:249)
	at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1182)
	at groove.gui.SimulatorModel.finish(SimulatorModel.java:1149)
	at groove.gui.SimulatorModel.doSetStateAndMatch(SimulatorModel.java:439)
	at groove.gui.action.ApplyMatchAction.execute(ApplyMatchAction.java:39)
	at groove.gui.tree.RuleTree$MyMouseListener.mouseClicked(RuleTree.java:776)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6508)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4501)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Reported by: sjunges

**Comment by rensink** [comment]
I think I know what's going on here, and there should be enough information in your stack trace to fix it. Will look into it.

Original comment by: rensink
