### ISSUE TITLE
Assertion error when loading grammar

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#447]
Loading the attached grammar gives an assertion error (trace below).
From what I could understand, the problem is caused by considering the variable 'nod' to be part of the initial location, whereas it is in fact a local variable.
However, I'm not that knowledgeable in the new control implementation to be able to fix this...

Trace:
Exception in thread "AWT-EventQueue-0" java.lang.AssertionError
	at groove.control.instance.Assignment.enter(Assignment.java:204)
	at groove.control.instance.Step.computePrepareAssignments(Step.java:168)
	at groove.control.instance.Step.getPrepareAssignments(Step.java:156)
	at groove.lts.MatchCollector.extractBinding(MatchCollector.java:215)
	at groove.lts.MatchCollector.computeMatches(MatchCollector.java:111)
	at groove.lts.StateMatches.advanceFrame(StateMatches.java:164)
	at groove.lts.StateMatches.getAll(StateMatches.java:78)
	at groove.lts.AbstractGraphState.getMatches(AbstractGraphState.java:216)
	at groove.gui.tree.StateTree.createStateNode(StateTree.java:378)
[...]

Reported by: zambon

**Comment by rensink** [comment]
Original comment by: rensink

**Comment by rensink** [comment]
Fixed in the HEAD

(The control program was actually erroneous because the nod variable may fail to be initialised, but the static check didn't catch this case. Now it does.)

We should probably get another bug release out!


Original comment by: rensink

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
Forgot to close this, apparently

Original comment by: rensink
