### ISSUE TITLE
ArrayOutOfBoundsException in presence of a condition rule

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#448]
Exploring a specially crafted grammar (attached) in GROOVE 5.2.3 works flawlessly until I add an empty (therefore classified as condition, crashes with real conditions as well) rule which then gives an AOOB exception.

This bug appears if the grammar's control programm sets to (out-)parameters by applying to different rules and then combining those as in-parameters in a third rule. As the in this case completely unneeded and empty condition rule is added, this exploration crashes.

Exception in GROOVE java.lang.ArrayIndexOutOfBoundsException: -1
	at groove.control.Valuator.get(Valuator.java:41)
	at groove.lts.MatchCollector.extractBinding(MatchCollector.java:230)
	at groove.lts.MatchCollector.computeMatches(MatchCollector.java:111)
	at groove.lts.StateMatches.advanceFrame(StateMatches.java:164)
	at groove.lts.StateMatches.getAll(StateMatches.java:78)
	at groove.lts.AbstractGraphState.getMatches(AbstractGraphState.java:216)
	at groove.explore.strategy.ClosingStrategy.doNext(ClosingStrategy.java:40)
	at groove.explore.strategy.Strategy.play(Strategy.java:95)
	at groove.explore.Exploration.play(Exploration.java:252)
	at groove.gui.action.ExploreAction$ExploreThread.run(ExploreAction.java:408)

Reported by: cmur2

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink
