### ISSUE TITLE
Model Checker from command line throws IllegalArgumentException

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#449]
The Model Checker from command line throws an exception.
To reproduce the bug I used the counting.gps from the samples and a trivial property. The issue occurs also for other grammars and properties.

I am running the tool from Mac with the following VM
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)

For the counting.gps example these are the steps:

java -jar ModelChecker.jar -ctl 'AG(true)' -g ../samples/counting.gps/ start

Grammar:	counting
Start graph:	start
Control:	main
Exploration:	bfs / final / infinite
Timestamp:	Wed Aug 20 14:47:50 CEST 2014

Time (ms):          86
Space (kB):         981

States:       10
Transitions:  9

3 result states found: [s5, s7, s9]
java.lang.IllegalArgumentException: The model being checked does not have an unabiguous root node
	at groove.verify.CTLMarker.hasValue(CTLMarker.java:510)
	at groove.verify.CTLMarker.hasValue(CTLMarker.java:496)
	at groove.verify.CTLModelChecker.modelCheck(CTLModelChecker.java:123)
	at groove.verify.CTLModelChecker.run(CTLModelChecker.java:100)
	at groove.util.cli.GrooveCmdLineTool.start(GrooveCmdLineTool.java:80)
	at groove.verify.CTLModelChecker.execute(CTLModelChecker.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at groove.util.cli.GrooveCmdLineTool.tryExecute(GrooveCmdLineTool.java:180)
	at groove.verify.CTLModelChecker.main(CTLModelChecker.java:164)
	at groove.ModelChecker.main(ModelChecker.java:31)

Reported by: pvaly

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
Fixed in the HEAD; we'll do a new bug release soon.


Original comment by: rensink

**Comment by rensink** [comment]
Thank you,
The tool now works when ModelChecker invokes directly the generation of the state space but I experience the same bug when importing an existing state space.

To reproduce the bug (still with the counting example):

java  -jar Generator.jar -o ../samples/counting.gps/LTS.gxl ../samples/counting.gps/
Grammar:	counting
Start graph:	start
Control:	main
Exploration:	bfs / final / infinite
Timestamp:	Mon Aug 25 13:10:59 CEST 2014



Time (ms):          140
Space (kB):         720

States:       10
Transitions:  9

3 result states found: [s5, s7, s9]

LTS saved as ../samples/counting.gps/LTS.gxl


java  -jar Generator.jar -o ../samples/counting.gps/LTS.gxl ../samples/counting.gps/
Grammar:	counting
Start graph:	start
Control:	main
Exploration:	bfs / final / infinite
Timestamp:	Mon Aug 25 13:10:59 CEST 2014



Time (ms):          140
Space (kB):         720

States:       10
Transitions:  9

3 result states found: [s5, s7, s9]

LTS saved as ../samples/counting.gps/LTS.gxl

OK, AND THEN:

java  -jar ModelChecker.jar -ctl 'AG(true)' ../samples/counting.gps/LTS.gxl 
Model: ../samples/counting.gps/LTS.gxl
java.lang.IllegalArgumentException: The model being checked does not have an unabiguous root node
	at groove.verify.CTLMarker.hasValue(CTLMarker.java:510)
	at groove.verify.CTLMarker.hasValue(CTLMarker.java:496)
	at groove.verify.CTLModelChecker.modelCheck(CTLModelChecker.java:124)
	at groove.verify.CTLModelChecker.run(CTLModelChecker.java:101)
	at groove.util.cli.GrooveCmdLineTool.start(GrooveCmdLineTool.java:80)
	at groove.verify.CTLModelChecker.execute(CTLModelChecker.java:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at groove.util.cli.GrooveCmdLineTool.tryExecute(GrooveCmdLineTool.java:180)
	at groove.verify.CTLModelChecker.main(CTLModelChecker.java:175)
	at groove.ModelChecker.main(ModelChecker.java:31)


Original comment by: pvaly

**Comment by rensink** [comment]
- **status**: closed-fixed --> pending


Original comment by: rensink

**Comment by rensink** [comment]
Reopened as the bug is not gone when the checker is run on a previously generated state space

Original comment by: rensink

**Comment by rensink** [comment]
- **status**: pending --> closed-fixed


Original comment by: rensink

**Comment by rensink** [comment]
Was already fixed but not marked as such

Original comment by: rensink
