### ISSUE TITLE
NPE due to spurious comment marker in control

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#452]
The Simulator crashes with an NPE when loading the attached grammar.
The bug is triggered by an unbalanced '*/' at the end of the control program.

Trace:
Exception in GROOVE java.lang.NullPointerException
	at groove.control.parse.CtrlHelper.qualify(CtrlHelper.java:211)
	at groove.control.parse.CtrlParser.rule_name(CtrlParser.java:4213)
	at groove.control.parse.CtrlParser.call(CtrlParser.java:4070)
	at groove.control.parse.CtrlParser.expr_atom(CtrlParser.java:3747)
	at groove.control.parse.CtrlParser.expr2(CtrlParser.java:3349)
	at groove.control.parse.CtrlParser.expr(CtrlParser.java:3124)
	at groove.control.parse.CtrlParser.stat(CtrlParser.java:2447)
	at groove.control.parse.CtrlParser.block(CtrlParser.java:1569)
	at groove.control.parse.CtrlParser.recipe(CtrlParser.java:1036)
	at groove.control.parse.CtrlParser.program(CtrlParser.java:275)
	at groove.control.parse.CtrlTree.parse(CtrlTree.java:463)
	at groove.control.CtrlLoader.parse(CtrlLoader.java:82)
[...]

Reported by: zambon

**Comment by rensink** [comment]
Fixed in the HEAD

Original comment by: rensink

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink
