### ISSUE TITLE
Simulator crashes due to bad recipe header

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#455]
If you open the attached grammar you get the following exception:

Exception in GROOVE java.lang.IllegalArgumentException: No enum constant groove.control.CtrlType.)
	at java.lang.Enum.valueOf(Enum.java:236)
	at groove.control.CtrlType.valueOf(CtrlType.java:1)
	at groove.control.parse.CtrlTree.getCtrlType(CtrlTree.java:61)
	at groove.control.parse.CtrlHelper.getPars(CtrlHelper.java:302)
	at groove.control.parse.CtrlHelper.declareCtrlUnit(CtrlHelper.java:275)
	at groove.control.parse.CtrlParser.recipe(CtrlParser.java:1043)
	at groove.control.parse.CtrlParser.program(CtrlParser.java:275)
	at groove.control.parse.CtrlTree.parse(CtrlTree.java:463)
	at groove.control.CtrlLoader.parse(CtrlLoader.java:82)
	at groove.grammar.model.CompositeControlModel.compute(CompositeControlModel.java:71)
	at groove.grammar.model.CompositeControlModel.compute(CompositeControlModel.java:1)
	at groove.grammar.model.ResourceModel.synchronise(ResourceModel.java:170)
	at groove.grammar.model.ResourceModel.toResource(ResourceModel.java:129)
	at groove.grammar.model.GrammarModel.computeGrammar(GrammarModel.java:459)
	at groove.grammar.model.GrammarModel.initGrammar(GrammarModel.java:406)
	at groove.grammar.model.GrammarModel.getErrors(GrammarModel.java:350)
	at groove.grammar.model.GrammarModel.hasErrors(GrammarModel.java:357)
	at groove.gui.SimulatorModel.setGrammar(SimulatorModel.java:768)
	at groove.gui.action.LoadGrammarAction.load(LoadGrammarAction.java:152)
[..]

Reported by: zambon

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
Fixed in the HEAD.

This is due to the desire to keep parsing even after an error has occurred. It might well be that there are other bugs of this kind lurking around, which will emerge only if new combinations of control program syntax errors are tried out.

Original comment by: rensink
