### ISSUE TITLE
Cast exception when using functions

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#456]
If you load the attached grammar, you get the exception below.
This is caused by the function in file control.ForStmt.gcp. If we change it to a recipe the bug doesn't show.

Q: What is the difference between a function and a recipe now?
I'm assuming the a function is just a macro and its code gets inlined, whereas a recipe is a  self-contained execution unit (that can fail, terminate, etc).

Exception in GROOVE java.lang.ClassCastException: groove.control.Function cannot be cast to groove.grammar.Action
	at groove.control.parse.CtrlTree.toTerm(CtrlTree.java:246)
	at groove.control.parse.CtrlTree.toTerm(CtrlTree.java:175)
	at groove.control.parse.CtrlTree.toTerm(CtrlTree.java:175)
	at groove.control.parse.CtrlTree.toTerm(CtrlTree.java:175)
	at groove.control.parse.CtrlTree.toTerm(CtrlTree.java:175)
	at groove.control.parse.CtrlTree.toProcedure(CtrlTree.java:354)
	at groove.control.parse.CtrlTree.toProgram(CtrlTree.java:304)
	at groove.control.CtrlLoader.buildProgram(CtrlLoader.java:105)
	at groove.grammar.model.CompositeControlModel.compute(CompositeControlModel.java:81)
	at groove.grammar.model.CompositeControlModel.compute(CompositeControlModel.java:1)
	at groove.grammar.model.ResourceModel.synchronise(ResourceModel.java:170)
	at groove.grammar.model.ResourceModel.toResource(ResourceModel.java:129)
	at groove.grammar.model.GrammarModel.computeGrammar(GrammarModel.java:459)
	at groove.grammar.model.GrammarModel.initGrammar(GrammarModel.java:406)
	at groove.grammar.model.GrammarModel.getErrors(GrammarModel.java:350)
	at groove.grammar.model.GrammarModel.hasErrors(GrammarModel.java:357)
	at groove.gui.SimulatorModel.setGrammar(SimulatorModel.java:768)
[...]

Reported by: zambon

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
Fixed in the HEAD

A: The function body doesn't get inlined, recursion is allowed. (Or you might say it gets inlined dynamically.)

Essentially, a recipe is a function with an implicitly atomic body, the execution of which is represented as a single transition with the recipe name as label. Moreover, every rule called directly or indirectly in a recipe is no longer available as top-level rule. All this makes recipes behave like rules in many respects.

Functions, on the other hand, are merely placeholders (abstractions) for their bodies.

Original comment by: rensink
