### ISSUE TITLE
Nullptr exeption when adding a second @ to a forall

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#458]
Like the title states, I was creating a rule and just added an edge from an embargo node to a forall node when I got the following error.

Exception in GROOVE java.lang.NullPointerException
	at java.util.HashSet.<init>(HashSet.java:118)
	at groove.grammar.rule.RuleEdge.<init>(RuleEdge.java:55)
	at groove.grammar.rule.RuleFactory.createEdge(RuleFactory.java:97)
	at groove.match.plan.PlanSearchEngine$PlanData.createEdgeSearchItem(PlanSearchEngine.java:437)
	at groove.match.plan.PlanSearchEngine$PlanData.computePatternSearchItems(PlanSearchEngine.java:348)
	at groove.match.plan.PlanSearchEngine$PlanData.computeSearchItems(PlanSearchEngine.java:265)
	at groove.match.plan.PlanSearchEngine$PlanData.getPlan(PlanSearchEngine.java:219)
	at groove.match.plan.PlanSearchEngine.createMatcher(PlanSearchEngine.java:89)
	at groove.match.plan.PlanSearchEngine.createMatcher(PlanSearchEngine.java:1)
	at groove.match.Matcher.getSearchStrategy(Matcher.java:238)
	at groove.match.Matcher.traverse(Matcher.java:117)
	at groove.match.Matcher.find(Matcher.java:76)
	at groove.match.plan.ConditionSearchItem$NegConditionRecord.find(ConditionSearchItem.java:429)
	at groove.match.plan.AbstractSearchItem$SingularRecord.next(AbstractSearchItem.java:296)
	at groove.match.plan.PlanSearchStrategy$Search.find(PlanSearchStrategy.java:432)
	at groove.match.plan.PlanSearchStrategy.traverse(PlanSearchStrategy.java:83)
	at groove.match.Matcher.traverse(Matcher.java:117)
	at groove.match.Matcher.findAll(Matcher.java:92)
	at groove.match.plan.ConditionSearchItem$QuantifierRecord.find(ConditionSearchItem.java:336)
	at groove.match.plan.AbstractSearchItem$SingularRecord.next(AbstractSearchItem.java:296)
	at groove.match.plan.PlanSearchStrategy$Search.find(PlanSearchStrategy.java:432)
	at groove.match.plan.PlanSearchStrategy.traverse(PlanSearchStrategy.java:83)
	at groove.match.Matcher.traverse(Matcher.java:117)
	at groove.grammar.Rule.traverseMatches(Rule.java:462)
	at groove.lts.MatchCollector.computeMatches(MatchCollector.java:134)
	at groove.lts.StateMatches.advanceFrame(StateMatches.java:164)
	at groove.lts.StateMatches.getAll(StateMatches.java:78)
	at groove.lts.AbstractGraphState.getMatches(AbstractGraphState.java:216)
	at groove.gui.tree.StateTree.createStateNode(StateTree.java:378)
	at groove.gui.tree.StateTree.fill(StateTree.java:346)
	at groove.gui.tree.StateTree.refreshList(StateTree.java:326)
	at groove.gui.tree.StateTree.update(StateTree.java:236)
	at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1182)
	at groove.gui.SimulatorModel.finish(SimulatorModel.java:1149)
	at groove.gui.SimulatorModel.setGts(SimulatorModel.java:524)
	at groove.gui.SimulatorModel.setGts(SimulatorModel.java:542)
	at groove.gui.action.StartSimulationAction.execute(StartSimulationAction.java:37)
	at groove.gui.display.LTSDisplay$5.run(LTSDisplay.java:443)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Reported by: sjunges

**Comment by rensink** [comment]
And now, as soon as I open the grammar, I get (the same) nullptr exception.
I can send you the grammar via another channel, if it helps.

Exception in GROOVE java.lang.NullPointerException
	at java.util.HashSet.<init>(HashSet.java:118)
	at groove.grammar.rule.RuleEdge.<init>(RuleEdge.java:55)
	at groove.grammar.rule.RuleFactory.createEdge(RuleFactory.java:97)
	at groove.match.plan.PlanSearchEngine$PlanData.createEdgeSearchItem(PlanSearchEngine.java:437)
	at groove.match.plan.PlanSearchEngine$PlanData.computePatternSearchItems(PlanSearchEngine.java:348)
	at groove.match.plan.PlanSearchEngine$PlanData.computeSearchItems(PlanSearchEngine.java:265)
	at groove.match.plan.PlanSearchEngine$PlanData.getPlan(PlanSearchEngine.java:219)
	at groove.match.plan.PlanSearchEngine.createMatcher(PlanSearchEngine.java:89)
	at groove.match.plan.PlanSearchEngine.createMatcher(PlanSearchEngine.java:1)
	at groove.match.Matcher.getSearchStrategy(Matcher.java:238)
	at groove.match.Matcher.traverse(Matcher.java:117)
	at groove.match.Matcher.find(Matcher.java:76)
	at groove.match.plan.ConditionSearchItem$NegConditionRecord.find(ConditionSearchItem.java:429)
	at groove.match.plan.AbstractSearchItem$SingularRecord.next(AbstractSearchItem.java:296)
	at groove.match.plan.PlanSearchStrategy$Search.find(PlanSearchStrategy.java:432)
	at groove.match.plan.PlanSearchStrategy.traverse(PlanSearchStrategy.java:83)
	at groove.match.Matcher.traverse(Matcher.java:117)
	at groove.match.Matcher.findAll(Matcher.java:92)
	at groove.match.plan.ConditionSearchItem$QuantifierRecord.find(ConditionSearchItem.java:336)
	at groove.match.plan.AbstractSearchItem$SingularRecord.next(AbstractSearchItem.java:296)
	at groove.match.plan.PlanSearchStrategy$Search.find(PlanSearchStrategy.java:432)
	at groove.match.plan.PlanSearchStrategy.traverse(PlanSearchStrategy.java:83)
	at groove.match.Matcher.traverse(Matcher.java:117)
	at groove.grammar.Rule.traverseMatches(Rule.java:462)
	at groove.lts.MatchCollector.computeMatches(MatchCollector.java:134)
	at groove.lts.StateMatches.advanceFrame(StateMatches.java:164)
	at groove.lts.StateMatches.getAll(StateMatches.java:78)
	at groove.lts.AbstractGraphState.getMatches(AbstractGraphState.java:216)
	at groove.gui.tree.StateTree.createStateNode(StateTree.java:378)
	at groove.gui.tree.StateTree.fill(StateTree.java:346)
	at groove.gui.tree.StateTree.refreshList(StateTree.java:326)
	at groove.gui.tree.StateTree.update(StateTree.java:236)
	at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1182)
	at groove.gui.SimulatorModel.finish(SimulatorModel.java:1149)
	at groove.gui.SimulatorModel.setGts(SimulatorModel.java:524)
	at groove.gui.SimulatorModel.setGts(SimulatorModel.java:542)
	at groove.gui.action.StartSimulationAction.execute(StartSimulationAction.java:37)
	at groove.gui.display.LTSDisplay$5.run(LTSDisplay.java:443)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


Original comment by: sjunges

**Comment by rensink** [comment]
Please attach the grammar in SourceForge.

Original comment by: rensink

**Comment by rensink** [comment]
After removing this file from the grammar, I was able to work with it again.

Original comment by: sjunges

**Comment by rensink** [comment]
The bug is related to the type graph. Can you include that as well?

Original comment by: rensink

**Comment by rensink** [comment]
Sorry i missed your request. I've got the error again - and have no clue which rule is causing it.

Exception in GROOVE java.lang.NullPointerException
	at java.util.HashSet.<init>(HashSet.java:118)
	at groove.grammar.rule.RuleEdge.<init>(RuleEdge.java:55)
	at groove.grammar.rule.RuleFactory.createEdge(RuleFactory.java:97)
	at groove.match.plan.PlanSearchEngine$PlanData.createEdgeSearchItem(PlanSearchEngine.java:437)
	at groove.match.plan.PlanSearchEngine$PlanData.computePatternSearchItems(PlanSearchEngine.java:348)
	at groove.match.plan.PlanSearchEngine$PlanData.computeSearchItems(PlanSearchEngine.java:265)
	at groove.match.plan.PlanSearchEngine$PlanData.getPlan(PlanSearchEngine.java:219)
	at groove.match.plan.PlanSearchEngine.createMatcher(PlanSearchEngine.java:89)
	at groove.match.plan.PlanSearchEngine.createMatcher(PlanSearchEngine.java:1)
	at groove.match.Matcher.getSearchStrategy(Matcher.java:238)
	at groove.match.Matcher.traverse(Matcher.java:117)
	at groove.match.Matcher.find(Matcher.java:76)
	at groove.match.plan.ConditionSearchItem$NegConditionRecord.find(ConditionSearchItem.java:429)
	at groove.match.plan.AbstractSearchItem$SingularRecord.next(AbstractSearchItem.java:296)
	at groove.match.plan.PlanSearchStrategy$Search.find(PlanSearchStrategy.java:432)
	at groove.match.plan.PlanSearchStrategy.traverse(PlanSearchStrategy.java:83)
	at groove.match.Matcher.traverse(Matcher.java:117)
	at groove.match.Matcher.findAll(Matcher.java:92)
	at groove.match.plan.ConditionSearchItem$QuantifierRecord.find(ConditionSearchItem.java:336)
	at groove.match.plan.AbstractSearchItem$SingularRecord.next(AbstractSearchItem.java:296)
	at groove.match.plan.PlanSearchStrategy$Search.find(PlanSearchStrategy.java:432)
	at groove.match.plan.PlanSearchStrategy.traverse(PlanSearchStrategy.java:83)
	at groove.match.Matcher.traverse(Matcher.java:117)
	at groove.grammar.Rule.traverseMatches(Rule.java:462)
	at groove.lts.MatchCollector.computeMatches(MatchCollector.java:134)
	at groove.lts.StateMatches.advanceFrame(StateMatches.java:164)
	at groove.lts.StateMatches.getAll(StateMatches.java:78)
	at groove.lts.AbstractGraphState.getMatches(AbstractGraphState.java:216)
	at groove.gui.tree.StateTree.createStateNode(StateTree.java:378)
	at groove.gui.tree.StateTree.fill(StateTree.java:346)
	at groove.gui.tree.StateTree.refreshList(StateTree.java:326)
	at groove.gui.tree.StateTree.update(StateTree.java:236)
	at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1182)
	at groove.gui.SimulatorModel.finish(SimulatorModel.java:1149)
	at groove.gui.SimulatorModel.setGts(SimulatorModel.java:524)
	at groove.gui.SimulatorModel.setGts(SimulatorModel.java:542)
	at groove.gui.action.StartSimulationAction.execute(StartSimulationAction.java:37)
	at groove.gui.display.LTSDisplay$5.run(LTSDisplay.java:443)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Original comment by: sjunges

**Comment by rensink** [comment]
Fortunately, this time I'm able to reproduce the bug! I'll get on to it. --Arend

Original comment by: rensink

**Comment by rensink** [comment]
The rule triggering the bug is called newRule - removing it from the grammar will cause the thing to load again. Judging from the name, this might be a non-essential rule ;-) so hopefully you'll be able to continue for now while I puzzle out what is actually going wrong. --Arend

Original comment by: rensink

**Comment by rensink** [comment]
Next insight: the bug-triggering rule had a child-edge from a WSp to an InnerNode. That is not typable: WSps are DynGates which may have child-edges to Ords (which are InnerNodes) but not to the InnerNodes directly. Thus, if you need a rule like this, the workaround is to change the InnerNode target type to Ord. I'm including the newRule, thus modified, as attachment.

Now I'll go and make sure that this doesn't crash GROOVE any more...

Original comment by: rensink

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
Fixed in the HEAD; will be part of new release

Original comment by: rensink
