### ISSUE TITLE
ArrayOutOfBounds for generator.jar

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#459]
When invoking the generator via the command line, I get the following error.
It may be very well that the generated input .gst is corrupt (as it works for other files), but a clue what is actually wrong would be very helpful.

(Will send grammar via other channels if required)

java -jar ~/groove-5_4_0/bin/Generator.jar -D controlProgram=simple -f /tmp/adftpubqkkaxg0h/outputGST/outputDFT#.gst ../groove_grammar/dft.gps /tmp/adftpubqkkaxg0h/blablabla.gst
java.lang.ArrayIndexOutOfBoundsException: -18
        at groove.graph.StoreFactory.getNode(StoreFactory.java:52)
        at groove.graph.NodeFactory.createNode(NodeFactory.java:84)
        at groove.graph.NodeFactory.createNode(NodeFactory.java:52)
        at groove.graph.AGraph.addNode(AGraph.java:284)
        at groove.io.graph.AttrGraph.copyTo(AttrGraph.java:258)
        at groove.io.graph.AttrGraph.toPlainGraph(AttrGraph.java:274)
        at groove.util.Groove.loadGraph(Groove.java:108)
        at groove.transform.Transformer.computeStartGraph(Transformer.java:199)
        at groove.transform.Transformer.computeStartGraph(Transformer.java:212)
        at groove.transform.Transformer.explore(Transformer.java:175)
        at groove.explore.Generator.run(Generator.java:76)
        at groove.explore.Generator.run(Generator.java:1)
        at groove.util.cli.GrooveCmdLineTool.start(GrooveCmdLineTool.java:80)
        at groove.explore.Generator.execute(Generator.java:417)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at groove.util.cli.GrooveCmdLineTool.tryExecute(GrooveCmdLineTool.java:180)
        at groove.explore.Generator.main(Generator.java:407)
        at groove.Generator.main(Generator.java:30)

Reported by: sjunges

**Comment by rensink** [comment]
I get the same error when opening this in the simulator.

Exception in GROOVE java.lang.ArrayIndexOutOfBoundsException: -11
	at groove.graph.StoreFactory.getNode(StoreFactory.java:52)
	at groove.graph.NodeFactory.createNode(NodeFactory.java:84)
	at groove.graph.NodeFactory.createNode(NodeFactory.java:52)
	at groove.graph.AGraph.addNode(AGraph.java:284)
	at groove.grammar.aspect.AspectGraph.toPlainGraph(AspectGraph.java:187)
	at groove.io.store.DefaultFileSystemStore.doPutGraphs(DefaultFileSystemStore.java:373)
	at groove.io.store.DefaultFileSystemStore.putGraphs(DefaultFileSystemStore.java:349)
	at groove.io.external.Importers.doChosenImport(Importers.java:107)
	at groove.io.external.Importers.doImport(Importers.java:63)
	at groove.gui.action.ImportAction.execute(ImportAction.java:22)
	at groove.gui.action.SimulatorAction.actionPerformed(SimulatorAction.java:231)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Original comment by: sjunges
