### ISSUE TITLE
Non reproducable bug at start up.

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#460]
I got this. Copied the error message, but could not reproduce.

Exception in GROOVE java.lang.NullPointerException
	at groove.grammar.model.ControlModel.compute(ControlModel.java:60)
	at groove.grammar.model.ControlModel.compute(ControlModel.java:1)
	at groove.grammar.model.ResourceModel.synchronise(ResourceModel.java:170)
	at groove.grammar.model.ResourceModel.toResource(ResourceModel.java:129)
	at groove.gui.action.PreviewControlAction.getTemplates(PreviewControlAction.java:107)
	at groove.gui.action.PreviewControlAction.refresh(PreviewControlAction.java:84)
	at groove.gui.action.ActionStore.refreshActions(ActionStore.java:81)
	at groove.gui.action.ActionStore.update(ActionStore.java:59)
	at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1182)
	at groove.gui.SimulatorModel.finish(SimulatorModel.java:1149)
	at groove.gui.SimulatorModel.setDisplay(SimulatorModel.java:1050)
	at groove.gui.UserSettings$2.run(UserSettings.java:138)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1654)
	at java.awt.Component.setVisible(Component.java:1606)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at groove.gui.dialog.BugReportDialog.<init>(BugReportDialog.java:104)
	at groove.Simulator$1.uncaughtException(Simulator.java:36)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Reported by: sjunges

**Comment by rensink** [comment]
- **status**: open --> closed-wont-fix
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
The non-reproducibility suggests a concurrency error. From the stack trace it appears this occurred while setting up a bug dialog (probably SF 459?) for another exception. I'm going to close this as unsolved - a bit frustrating, but the priority is just too low. --Arend


Original comment by: rensink
