### ISSUE TITLE
NullPointerException in the FrozenDeltaApplier

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#461]
I tried to reproduce [#458]. Instead of the bug I searched for, i got this: 

Exception in GROOVE java.lang.NullPointerException
	at groove.transform.FrozenDeltaApplier.applyDelta(FrozenDeltaApplier.java:39)
	at groove.transform.FrozenDeltaApplier.applyDelta(FrozenDeltaApplier.java:51)
	at groove.grammar.host.DeltaHostGraph.initData(DeltaHostGraph.java:342)
	at groove.grammar.host.DeltaHostGraph.nodeSet(DeltaHostGraph.java:196)
	at groove.graph.AGraph.nodeCount(AGraph.java:51)
	at groove.graph.iso.CertificateStrategy.initCertificates(CertificateStrategy.java:134)
	at groove.graph.iso.CertificateStrategy.computeCertificates(CertificateStrategy.java:116)
	at groove.graph.iso.CertificateStrategy.getGraphCertificate(CertificateStrategy.java:80)
	at groove.lts.GTS$StateSet.getCode(GTS.java:926)
	at groove.lts.GTS$StateSet.getCode(GTS.java:1)
	at groove.util.collect.TreeHashSet.put(TreeHashSet.java:389)
	at groove.lts.GTS.addState(GTS.java:177)
	at groove.lts.GTS.startState(GTS.java:113)
	at groove.gui.SimulatorModel.setGts(SimulatorModel.java:510)
	at groove.gui.SimulatorModel.setGts(SimulatorModel.java:542)
	at groove.gui.action.StartSimulationAction.execute(StartSimulationAction.java:37)
	at groove.gui.display.LTSDisplay$5.run(LTSDisplay.java:443)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Reported by: sjunges

**Comment by rensink** [comment]
The grammar contains rule errors; after disabling the erroneous rules, exploration works fine for me. Given the date of this error report, and the fact that the bug referred to has been closed, I'm going to close this one as well.

Original comment by: rensink
