### ISSUE TITLE
Exception in InitializerError

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#463]
When opening the Simulator (Groove 5.5.0) in Debian 8.0 with OpenJDK-7 I get the following error. I cannot reproduce this on ArchLinux with OpenJDK-8.

Exception in GROOVE java.lang.ExceptionInInitializerError
	at groove.control.template.TemplateBuilder.build(TemplateBuilder.java:83)
	at groove.control.template.Program.setFixed(Program.java:744)
	at groove.control.CtrlLoader.buildProgram(CtrlLoader.java:119)
	at groove.grammar.model.CompositeControlModel.compute(CompositeControlModel.java:81)
	at groove.grammar.model.CompositeControlModel.compute(CompositeControlModel.java:1)
	at groove.grammar.model.ResourceModel.synchronise(ResourceModel.java:166)
	at groove.grammar.model.CompositeControlModel.getRecipes(CompositeControlModel.java:119)
	at groove.grammar.model.RuleModel.getRecipes(RuleModel.java:139)
	at groove.grammar.model.RuleModel.hasRecipes(RuleModel.java:144)
	at groove.grammar.model.RuleModel.isEnabled(RuleModel.java:134)
	at groove.grammar.model.GrammarModel.computeGrammar(GrammarModel.java:447)
	at groove.grammar.model.GrammarModel.initGrammar(GrammarModel.java:406)
	at groove.grammar.model.GrammarModel.getErrors(GrammarModel.java:350)
	at groove.grammar.model.GrammarModel.hasErrors(GrammarModel.java:357)
	at groove.gui.SimulatorModel.setGrammar(SimulatorModel.java:768)
	at groove.gui.action.LoadGrammarAction.load(LoadGrammarAction.java:152)
	at groove.gui.action.LoadGrammarAction.load(LoadGrammarAction.java:75)
	at groove.gui.action.LoadGrammarAction.execute(LoadGrammarAction.java:51)
	at groove.gui.action.SimulatorAction.actionPerformed(SimulatorAction.java:231)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3311)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.IllegalArgumentException
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1310)
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1198)
	at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:89)
	at groove.util.ThreadPool.<init>(ThreadPool.java:30)
	at groove.util.ThreadPool.<clinit>(ThreadPool.java:81)

Reported by: sjunges

**Comment by rensink** [comment]
By the way, using the generator yields a printed "null."

Original comment by: sjunges

**Comment by rensink** [comment]
I was able to open your grammar in my system without an error. I'm using ArchLinux:

$ uname -a
Linux unit01 3.18.4-1-ARCH #1 SMP PREEMPT Tue Jan 27 20:45:02 CET 2015 x86_64 GNU/Linux

with the Oracle JDK 7:

$ java -version
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

My experience with OpenJDK was always a bit problematic as there was usually some incompatibilities with the Oracle(Sun) JDK that prevented me from running Groove.

If I understood your last post correctly, you're also having problems with the Oracle JDK (7 and 8), is that right? Does this happens both in ArchLinux and Debian? Could you provide the output of the commands above from you system?


Original comment by: zambon

**Comment by rensink** [comment]
Let me first emphasize that I run into trouble with any grammar - also generating a new one is not possible.

Furthermore, I'm sure that this is a concurrency issue. Let me give you the requested info from different machines:

Notice that if i change the number of processors in the virtual machine to two, the error does NOT occur!

--------------------------------------------------------
From the virtual machine (error above):

$ uname -a
Linux ftanalysis-vm 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt4-3 (2015-02-03) x86_64 GNU/Linux

$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)


--------------------------------------------------------
From a server (the generator runs, which it does not on the virtual machine):

$ uname -a
Linux kallisto 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 GNU/Linux

$ java -version
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-2)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
--------------------------------------------------------
From my laptop (both generator and simulator working)

$ uname -a
Linux flatland 3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux

$ java -version
openjdk version "1.8.0_31"
OpenJDK Runtime Environment (build 1.8.0_31-b13)
OpenJDK 64-Bit Server VM (build 25.31-b07, mixed mode)



Original comment by: sjunges

**Comment by rensink** [comment]
Yes, this is certainly a concurrency problem. The exception error points to a line where a thread pool is created. My guess is that the Java VM makes a native call to the OS to create threads and that this call is failing.

This may be unlikely but for now the only explanation that I can come up is some sort of incompatibility in the Debian kernel...

Original comment by: zambon

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
Fixed in release 5.5.1. This problem occurred on any platform where Runtime.getRuntime().availableProcessors() would return 1.

Original comment by: rensink
