### ISSUE TITLE
NPE in LTS view

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#464]
If you double-click a state in the LTS panel the Simulator crashes with the following NPE stack:

Exception in GROOVE java.lang.NullPointerException
	at groove.gui.tree.StateTree$StateTreeNode.isResult(StateTree.java:687)
	at groove.gui.tree.StateTree$StateTreeNode.getIcon(StateTree.java:668)
	at groove.gui.tree.DisplayTreeCellRenderer.getTreeCellRendererComponent(DisplayTreeCellRenderer.java:58)
	at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2806)
[...]

Reported by: zambon

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
Couldn't reproduce, but the exception was clear enough to find and repair the cause.

Original comment by: rensink
