### ISSUE TITLE
Groove crash when retyping attributes together with type graph

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#467]
Hello folks,

Groove crashed, when I tried to change the type of an attribute node from "int" to "real" in the Graph view. The following exception was thrown:
Exception in GROOVE java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at groove.algebra.JavaRealAlgebra.toTerm(JavaRealAlgebra.java:119)
	at groove.grammar.host.ValueNode.getTerm(ValueNode.java:87)
	at groove.grammar.aspect.GraphConverter.toAspectMap(GraphConverter.java:132)
	at groove.gui.display.StateDisplay.getAspectMap(StateDisplay.java:737)
	at groove.gui.display.StateDisplay.getAspectJModel(StateDisplay.java:475)
	at groove.gui.display.StateDisplay.displayState(StateDisplay.java:427)
	at groove.gui.display.StateDisplay.startSimulation(StateDisplay.java:341)
	at groove.gui.display.StateDisplay.update(StateDisplay.java:303)
	at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1192)
	at groove.gui.SimulatorModel.finish(SimulatorModel.java:1159)
	at groove.gui.SimulatorModel.setGTS(SimulatorModel.java:528)
	at groove.gui.SimulatorModel.setGTS(SimulatorModel.java:542)
	at groove.gui.action.StartSimulationAction.execute(StartSimulationAction.java:37)
	at groove.gui.display.LTSDisplay$5.run(LTSDisplay.java:446)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

For reproducability:
1. create a type graph with, say, an Object type (type:Object) that also has an 'x' attribute of type 'int' (int:x)
2. create a start Graph with an Object-type node and an Attribute node of type int. Create an 'x' edge between them.
3. Back at the type graph, change the attribute type of the Object from 'int' to 'real'. (The parser complains in red.)
4. Back at the start graph, double click the attribute node and change it from 'int' to 'real'. When saving this change, Groove crashes.

When reopening the files, Groove immediately crashes. Thus, I changed the start graph back to 'int' in a text editor so that you can open it with 5.5.5 of Groove.

Best,
CBA

Reported by: becker-asano

**Comment by rensink** [comment]
Hello folks,

I found the cause for the crash:
In the Simulator (i.e. visual editor), if one creates a "real" attribute node with `real:1`, then Groove crashes when the graph is being saved, but `real:1.0` works fine. The same applies to renaming "int:1" to "real:1" and then saving.
This is particularly annoying, because of the App crashing also when reopening the erroneous project folder after restart. One has to first edit the graph in a text editor, before it can be opened again.

I will try to fix the bug in the sources. I'll keep you updated.

Best,
CBA

Original comment by: becker-asano

**Comment by rensink** [comment]
Thanks for your report. In fact you do not need the type prefix (just 1.0 or 1. will do) but of course it's a bug, and a rather nasty one at that since it corrupts the grammar, as you remarked. Will upload a new release tonight.

Original comment by: rensink

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink
