### ISSUE TITLE
Imported abstract type gives an NPE

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#470]
If you try to add a node to the type graph with both the import: and abs: prefixes, the simulator crashes with the following NPE (import of non-abstract types works fine):

Exception in GROOVE java.lang.NullPointerException
	at groove.gui.look.LabelValue.getDataLines(LabelValue.java:774)
	at groove.gui.look.LabelValue.getTypeNodeLabel(LabelValue.java:231)
	at groove.gui.look.LabelValue.getJVertexLabel(LabelValue.java:104)
	at groove.gui.look.LabelValue.get(LabelValue.java:84)
	at groove.gui.look.LabelValue.get(LabelValue.java:1)
	at groove.gui.jgraph.AJCell.refreshVisual(AJCell.java:190)
	at groove.gui.jgraph.AJCell.getVisuals(AJCell.java:205)
	at groove.gui.jgraph.AspectJModel.syncGraph(AspectJModel.java:236)
	at groove.gui.jgraph.AspectJModel.fireGraphChanged(AspectJModel.java:478)
	at org.jgraph.graph.DefaultGraphModel$GraphModelEdit.execute(Unknown Source)
	at org.jgraph.graph.DefaultGraphModel.edit(Unknown Source)
	at org.jgraph.graph.DefaultGraphModel.edit(Unknown Source)
	at org.jgraph.graph.GraphLayoutCache.edit(Unknown Source)
	at org.jgraph.graph.GraphLayoutCache.valueForCellChanged(Unknown Source)
    [...]

Reported by: zambon

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
An oldie, I think this was!

Original comment by: rensink
