### ISSUE TITLE
Creating a rule gives an NPE in HEAD

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#471]
Adding a new rule with the current HEAD version of the Simulator gives the following NPE:

Exception in GROOVE java.lang.NullPointerException
	at groove.util.Properties.parseProperty(Properties.java:107)
	at groove.grammar.GrammarProperties.getActiveNames(GrammarProperties.java:294)
	at groove.io.store.DefaultFileSystemStore.doEnableDefaultName(DefaultFileSystemStore.java:196)
	at groove.io.store.DefaultFileSystemStore.doPutGraphs(DefaultFileSystemStore.java:383)
	at groove.io.store.DefaultFileSystemStore.putGraphs(DefaultFileSystemStore.java:350)
	at groove.gui.SimulatorModel.doAddGraph(SimulatorModel.java:225)
	at groove.gui.action.NewAction.execute(NewAction.java:30)
	at groove.gui.action.SimulatorAction.actionPerformed(SimulatorAction.java:228)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    [...]

Reported by: zambon

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
Regression bug... now fixed in the HEAD

Original comment by: rensink
