### ISSUE TITLE
Uncaught exception on loading grammar

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#481]
Using groove-5_7_2 I get an uncaught exception when loading a grammar.

As a blind user I use the screen reader NVDA (https://www.nvaccess.org/) which makes use of the Java access bridge (http://www.oracle.com/technetwork/articles/javase/index-jsp-136191.html).
Looking at the stack trace that's probably where the problem is.
The grammar I'm trying to open has only an empty start state. It has no nodes or edges yet.

Exception in GROOVE java.lang.NullPointerException
	at javax.swing.JTabbedPane.indexOfTab(Unknown Source)
	at javax.swing.JTabbedPane$Page.getAccessibleStateSet(Unknown Source)
	at com.sun.java.accessibility.util.AccessibilityEventMonitor$AccessibilityEventListener.installListeners(AccessibilityEventMonitor.java:159)
	at com.sun.java.accessibility.util.AccessibilityEventMonitor$AccessibilityEventListener.installListeners(AccessibilityEventMonitor.java:148)
	at com.sun.java.accessibility.util.AccessibilityEventMonitor$AccessibilityEventListener.installListeners(AccessibilityEventMonitor.java:196)
	at com.sun.java.accessibility.util.AccessibilityEventMonitor$AccessibilityEventListener.installListeners(AccessibilityEventMonitor.java:148)
	at com.sun.java.accessibility.util.AccessibilityEventMonitor$AccessibilityEventListener.installListeners(AccessibilityEventMonitor.java:196)
	at com.sun.java.accessibility.util.AccessibilityEventMonitor$AccessibilityEventListener.propertyChange(AccessibilityEventMonitor.java:335)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at javax.accessibility.AccessibleContext.firePropertyChange(Unknown Source)
	at java.awt.Container$AccessibleAWTContainer$AccessibleContainerHandler.componentAdded(Unknown Source)
	at java.awt.AWTEventMulticaster.componentAdded(Unknown Source)
	at java.awt.Container.processContainerEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.Container.addImpl(Unknown Source)
	at javax.swing.JTabbedPane.insertTab(Unknown Source)
	at groove.gui.display.DisplaysPanel.attach(DisplaysPanel.java:367)
	at groove.gui.display.DisplaysPanel.showOrHideTab(DisplaysPanel.java:98)
	at groove.gui.display.DisplaysPanel.update(DisplaysPanel.java:231)
	at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1190)
	at groove.gui.SimulatorModel.finish(SimulatorModel.java:1159)
	at groove.gui.SimulatorModel.setGrammar(SimulatorModel.java:818)
	at groove.gui.action.LoadGrammarAction.load(LoadGrammarAction.java:150)
	at groove.gui.action.LoadGrammarFromHistoryAction.execute(LoadGrammarFromHistoryAction.java:44)
	at groove.gui.action.SimulatorAction.actionPerformed(SimulatorAction.java:226)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicPopupMenuUI$Actions.doReturn(Unknown Source)
	at javax.swing.plaf.basic.BasicPopupMenuUI$Actions.actionPerformed(Unknown Source)
	at javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at javax.swing.JComponent.processKeyBinding(Unknown Source)
	at javax.swing.KeyboardManager.fireBinding(Unknown Source)
	at javax.swing.KeyboardManager.fireKeyboardAction(Unknown Source)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(Unknown Source)
	at javax.swing.JComponent.processKeyBindings(Unknown Source)
	at javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Reported by: hmulder

**Comment by rensink** [comment]
This may be nasty.  As far as I can make out from the stack trace, the accessibility library is trying to install a listener to a component that is not yet there - to be more precise: at tab that is in the process of being added to a JTabbedPane. I'll take a look, but reproducing the error in the first place may not be easy.

Original comment by: rensink

**Comment by rensink** [comment]
- **status**: open --> accepted
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
I forgot to mention it is in Windows.
I think it should be possible to reproduce. For the Java access bridge 
you (also) need an x86 JVM. Then it is a matter of checking the box at 
Ease of Access Center -> Use the computer without a display -> Enable 
Java Access Bridge. (That is on Windows 10; I'm not sure where the 
setting is in other versions of Windows)

On 3/7/2018 8:46 AM, Arend Rensink wrote:
>
> This may be nasty. As far as I can make out from the stack trace, the 
> accessibility library is trying to install a listener to a component 
> that is not yet there - to be more precise: at tab that is in the 
> process of being added to a JTabbedPane. I'll take a look, but 
> reproducing the error in the first place may not be easy.
>
> ------------------------------------------------------------------------
>
> *[bugs:#481] <https://sourceforge.net/p/groove/bugs/481/> Uncaught 
> exception on loading grammar*
>
> *Status:* open
> *Created:* Wed Mar 07, 2018 07:15 AM UTC by Henk Mulder
> *Last Updated:* Wed Mar 07, 2018 07:15 AM UTC
> *Owner:* nobody
>
> Using groove-5_7_2 I get an uncaught exception when loading a grammar.
>
> As a blind user I use the screen reader NVDA 
> (https://www.nvaccess.org/) which makes use of the Java access bridge 
> (http://www.oracle.com/technetwork/articles/javase/index-jsp-136191.html).
> Looking at the stack trace that's probably where the problem is.
> The grammar I'm trying to open has only an empty start state. It has 
> no nodes or edges yet.
>
> Exception in GROOVE java.lang.NullPointerException
> at javax.swing.JTabbedPane.indexOfTab(Unknown Source)
> at javax.swing.JTabbedPane$Page.getAccessibleStateSet(Unknown Source)
> at 
> com.sun.java.accessibility.util.AccessibilityEventMonitor$AccessibilityEventListener.installListeners(AccessibilityEventMonitor.java:159)
> at 
> com.sun.java.accessibility.util.AccessibilityEventMonitor$AccessibilityEventListener.installListeners(AccessibilityEventMonitor.java:148)
> at 
> com.sun.java.accessibility.util.AccessibilityEventMonitor$AccessibilityEventListener.installListeners(AccessibilityEventMonitor.java:196)
> at 
> com.sun.java.accessibility.util.AccessibilityEventMonitor$AccessibilityEventListener.installListeners(AccessibilityEventMonitor.java:148)
> at 
> com.sun.java.accessibility.util.AccessibilityEventMonitor$AccessibilityEventListener.installListeners(AccessibilityEventMonitor.java:196)
> at 
> com.sun.java.accessibility.util.AccessibilityEventMonitor$AccessibilityEventListener.propertyChange(AccessibilityEventMonitor.java:335)
> at java.beans.PropertyChangeSupport.fire(Unknown Source)
> at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
> at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
> at javax.accessibility.AccessibleContext.firePropertyChange(Unknown 
> Source)
> at 
> java.awt.Container$AccessibleAWTContainer$AccessibleContainerHandler.componentAdded(Unknown 
> Source)
> at java.awt.AWTEventMulticaster.componentAdded(Unknown Source)
> at java.awt.Container.processContainerEvent(Unknown Source)
> at java.awt.Container.processEvent(Unknown Source)
> at java.awt.Component.dispatchEventImpl(Unknown Source)
> at java.awt.Container.dispatchEventImpl(Unknown Source)
> at java.awt.Component.dispatchEvent(Unknown Source)
> at java.awt.Container.addImpl(Unknown Source)
> at javax.swing.JTabbedPane.insertTab(Unknown Source)
> at groove.gui.display.DisplaysPanel.attach(DisplaysPanel.java:367)
> at groove.gui.display.DisplaysPanel.showOrHideTab(DisplaysPanel.java:98)
> at groove.gui.display.DisplaysPanel.update(DisplaysPanel.java:231)
> at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1190)
> at groove.gui.SimulatorModel.finish(SimulatorModel.java:1159)
> at groove.gui.SimulatorModel.setGrammar(SimulatorModel.java:818)
> at groove.gui.action.LoadGrammarAction.load(LoadGrammarAction.java:150)
> at 
> groove.gui.action.LoadGrammarFromHistoryAction.execute(LoadGrammarFromHistoryAction.java:44)
> at 
> groove.gui.action.SimulatorAction.actionPerformed(SimulatorAction.java:226)
> at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
> at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
> at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
> at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
> at javax.swing.AbstractButton.doClick(Unknown Source)
> at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
> at javax.swing.plaf.basic.BasicPopupMenuUI$Actions.doReturn(Unknown 
> Source)
> at 
> javax.swing.plaf.basic.BasicPopupMenuUI$Actions.actionPerformed(Unknown 
> Source)
> at javax.swing.SwingUtilities.notifyAction(Unknown Source)
> at javax.swing.JComponent.processKeyBinding(Unknown Source)
> at javax.swing.KeyboardManager.fireBinding(Unknown Source)
> at javax.swing.KeyboardManager.fireKeyboardAction(Unknown Source)
> at javax.swing.JComponent.processKeyBindingsForAllComponents(Unknown 
> Source)
> at javax.swing.JComponent.processKeyBindings(Unknown Source)
> at javax.swing.JComponent.processKeyEvent(Unknown Source)
> at java.awt.Component.processEvent(Unknown Source)
> at java.awt.Container.processEvent(Unknown Source)
> at java.awt.Component.dispatchEventImpl(Unknown Source)
> at java.awt.Container.dispatchEventImpl(Unknown Source)
> at java.awt.Component.dispatchEvent(Unknown Source)
> at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
> at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
> at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown 
> Source)
> at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown 
> Source)
> at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
> at java.awt.Component.dispatchEventImpl(Unknown Source)
> at java.awt.Container.dispatchEventImpl(Unknown Source)
> at java.awt.Window.dispatchEventImpl(Unknown Source)
> at java.awt.Component.dispatchEvent(Unknown Source)
> at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> at java.awt.EventQueue.access$500(Unknown Source)
> at java.awt.EventQueue$3.run(Unknown Source)
> at java.awt.EventQueue$3.run(Unknown Source)
> at java.security.AccessController.doPrivileged(Native Method)
> at 
> java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown 
> Source)
> at 
> java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown 
> Source)
> at java.awt.EventQueue$4.run(Unknown Source)
> at java.awt.EventQueue$4.run(Unknown Source)
> at java.security.AccessController.doPrivileged(Native Method)
> at 
> java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown 
> Source)
> at java.awt.EventQueue.dispatchEvent(Unknown Source)
> at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> at java.awt.EventDispatchThread.run(Unknown Source)
>
> ------------------------------------------------------------------------
>
> Sent from sourceforge.net because you indicated interest in 
> https://sourceforge.net/p/groove/bugs/481/
>
> To unsubscribe from further messages, please visit 
> https://sourceforge.net/auth/subscriptions/
>



Original comment by: hmulder

**Comment by rensink** [comment]
- **status**: accepted --> closed-wont-fix


Original comment by: rensink

**Comment by rensink** [comment]
Unfortunately, this is due to the accessibility library; I see no way to fix it. A workaround is not to invoke groove.Simulator (which catches any thrown exceptions in an error window and then exit) but instead groove.gui.Simulator (which just ignores all runtime exceptions); it turns out that the accessibility exception does not crash the system.

Concretely, a way to implement the workaround is: modify the manifest of Simulator.jar so that the last line (where it invokes its main class) does not reat java.Simulator but java.gui.Simulator

Original comment by: rensink
