### ISSUE TITLE
rule_name -> NullPointer

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#488]
With the following input:
~~~
...
while (*.eq(i,0)) {
...
~~~

I get the following trace:
~~~
Exception in GROOVE java.lang.NullPointerException
	at groove.control.parse.CtrlHelper.registerCall(CtrlHelper.java:369)
	at groove.control.parse.CtrlParser.call(CtrlParser.java:3563)
	at groove.control.parse.CtrlParser.cond_atom(CtrlParser.java:2660)
	at groove.control.parse.CtrlParser.cond(CtrlParser.java:2452)
	at groove.control.parse.CtrlParser.stat(CtrlParser.java:1771)
	at groove.control.parse.CtrlParser.block(CtrlParser.java:1382)
	at groove.control.parse.CtrlParser.recipe(CtrlParser.java:926)
	at groove.control.parse.CtrlParser.program(CtrlParser.java:268)
	at groove.control.parse.CtrlTree.parse(CtrlTree.java:487)
	at groove.control.CtrlLoader.addControl(CtrlLoader.java:81)
	at groove.grammar.model.CompositeControlModel.compute(CompositeControlModel.java:68)
	at groove.grammar.model.CompositeControlModel.compute(CompositeControlModel.java:1)
	at groove.grammar.model.ResourceModel.synchronise(ResourceModel.java:142)
	at groove.grammar.model.ResourceModel.toResource(ResourceModel.java:100)
	at groove.grammar.model.GrammarModel.computeGrammar(GrammarModel.java:473)
	at groove.grammar.model.GrammarModel.initGrammar(GrammarModel.java:418)
	at groove.grammar.model.GrammarModel.getErrors(GrammarModel.java:361)
	at groove.grammar.model.GrammarModel.hasErrors(GrammarModel.java:368)
	at groove.gui.action.ExplorationDialogAction.refresh(ExplorationDialogAction.java:25)
	at groove.gui.action.ActionStore.refreshActions(ActionStore.java:81)
	at groove.gui.action.ActionStore.update(ActionStore.java:59)
	at groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1195)
	at groove.gui.SimulatorModel.finish(SimulatorModel.java:1164)
	at groove.gui.SimulatorModel.doAddText(SimulatorModel.java:266)
	at groove.gui.action.SaveAction.doSaveText(SaveAction.java:145)
	at groove.gui.action.SaveAction.execute(SaveAction.java:73)
	at groove.gui.action.SimulatorAction.actionPerformed(SimulatorAction.java:226)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2943)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6316)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:834)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1102)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:973)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:799)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

~~~

Reported by: nobody

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
Resolved in HEAD

Original comment by: rensink
