### ISSUE TITLE
NullPointers in console output

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#489]
When running the Groove Simulator from the console the following exception is printed multiple times:
~~~
java.lang.NullPointerException
        at org.GNOME.Accessibility.AtkWrapper.dispatchFocusEvent(AtkWrapper.java:390)
        at org.GNOME.Accessibility.AtkWrapper$4.eventDispatched(AtkWrapper.java:333)
        at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2427)
        at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2318)
        at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2318)
        at java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2277)
        at java.awt.Component.dispatchEventImpl(Component.java:4785)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1014)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:638)
        at java.awt.Component.dispatchEventImpl(Component.java:4760)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
~~~

I started the Simulator with the following command:
~~~
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -XX:SoftRefLRUPolicyMSPerMB=10 -disablesystemassertions -Xmx12g -Xms8g -d64 -jar bin/Simulator.jar
~~~

Reported by: nobody

**Comment by rensink** [comment]
I can't reproduce the error, but the stack trace strongly suggests some GUI-internal stuff that I wouldn't know how to fix anyway. Might even have to do with the JVM used. Since the bug seems non-lethal, I'll ignore it.

Original comment by: rensink
