### ISSUE TITLE
Missing system.properties makes an NullPointerException

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#491]
When executing the following command:
~~~
java8 -XX:SoftRefLRUPolicyMSPerMB=10 -Xmx11g -Xms8g -jar ./bin/Generator.jar connect_n/play-double-edged-strategy-game.gps s333double
~~~

If the x.gps folder does not have a system.properties then the following exception will appear:
~~~
java.lang.NullPointerException
        at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
        at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
        at java.nio.file.Paths.get(Paths.java:84)
        at groove.util.parse.Parser$PathParser.parse(Parser.java:324)
        at groove.util.parse.Parser$PathParser.parse(Parser.java:1)
        at groove.grammar.GrammarProperties.check(GrammarProperties.java:443)
        at groove.grammar.model.GrammarModel.computeGrammar(GrammarModel.java:482)
        at groove.grammar.model.GrammarModel.initGrammar(GrammarModel.java:418)
        at groove.grammar.model.GrammarModel.toGrammar(GrammarModel.java:408)
        at groove.transform.Transformer.explore(Transformer.java:118)
        at groove.transform.Transformer.explore(Transformer.java:143)
        at groove.transform.Transformer.explore(Transformer.java:183)
        at groove.explore.Generator.run(Generator.java:75)
        at groove.explore.Generator.run(Generator.java:1)
        at groove.util.cli.GrooveCmdLineTool.start(GrooveCmdLineTool.java:81)
        at groove.explore.Generator.execute(Generator.java:413)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groove.util.cli.GrooveCmdLineTool.tryExecute(GrooveCmdLineTool.java:179)
        at groove.explore.Generator.main(Generator.java:403)
        at groove.Generator.main(Generator.java:30)
~~~

The program then exits.

Reported by: nobody

**Comment by rensink** [comment]
- **status**: open --> closed-out-of-date
- **assigned_to**: Arend Rensink


Original comment by: rensink
