### ISSUE TITLE
using a names existential crashes

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#494]
A nullpointer crash happens when you create the following graph:

Exception in GROOVE java.lang.NullPointerException
	at groove.grammar.type.TypeGraph.computeNodeImages(TypeGraph.java:785)
	at groove.grammar.type.TypeGraph.analyzeRule(TypeGraph.java:465)
	at groove.grammar.model.RuleModel$Level3.toTypedGraph(RuleModel.java:2081)
	at groove.grammar.model.RuleModel$Level3.<init>(RuleModel.java:2018)
	at groove.grammar.model.RuleModel$LevelTree.buildLevels3(RuleModel.java:1040)
	at groove.grammar.model.RuleModel$LevelTree.<init>(RuleModel.java:724)
	at groove.grammar.model.RuleModel.compute(RuleModel.java:282)
	at groove.grammar.model.RuleModel.compute(RuleModel.java:1)
	at groove.grammar.model.ResourceModel.synchronise(ResourceModel.java:142)
	at groove.grammar.model.RuleModel.getTypeMap(RuleModel.java:335)
	at groove.gui.jgraph.AspectJEdge.getTypeMap(AspectJEdge.java:207)
	at groove.gui.jgraph.AspectJEdge.getKey(AspectJEdge.java:198)
	at groove.gui.jgraph.AspectJEdge.getKey(AspectJEdge.java:1)
	at groove.gui.jgraph.AJEdge.getKeys(AJEdge.java:280)
	at groove.gui.jgraph.AspectJEdge.getKeys(AspectJEdge.java:191)
	at groove.gui.tree.LabelFilter.computeEntries(LabelFilter.java:64)
	at groove.gui.tree.LabelFilter.addJCell(LabelFilter.java:81)
	at groove.gui.tree.LabelTree.updateFilter(LabelTree.java:240)
	at groove.gui.tree.TypeTree.updateFilter(TypeTree.java:208)
	at groove.gui.tree.LabelTree.updateModel(LabelTree.java:218)
	at groove.gui.tree.TypeTree$1.update(TypeTree.java:93)
	at java.util.Observable.notifyObservers(Unknown Source)
	at java.util.Observable.notifyObservers(Unknown Source)
	at groove.util.ChangeCount.increase(ChangeCount.java:32)
	at groove.gui.jgraph.AspectJModel.syncGraph(AspectJModel.java:256)
	at groove.gui.jgraph.AspectJModel.fireGraphChanged(AspectJModel.java:478)
	at org.jgraph.graph.DefaultGraphModel$GraphModelEdit.execute(Unknown Source)
	at org.jgraph.graph.DefaultGraphModel.edit(Unknown Source)
	at org.jgraph.graph.DefaultGraphModel.edit(Unknown Source)
	at org.jgraph.graph.GraphLayoutCache.edit(Unknown Source)
	at org.jgraph.graph.GraphLayoutCache.valueForCellChanged(Unknown Source)
	at org.jgraph.plaf.basic.BasicGraphUI.completeEditing(Unknown Source)
	at org.jgraph.plaf.basic.BasicGraphUI$CellEditorHandler.editingStopped(Unknown Source)
	at javax.swing.AbstractCellEditor.fireEditingStopped(Unknown Source)
	at javax.swing.AbstractCellEditor.stopCellEditing(Unknown Source)
	at groove.gui.jgraph.MultiLinedEditor$RealCellEditor$StopEditAction.actionPerformed(MultiLinedEditor.java:305)
	at javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at javax.swing.JComponent.processKeyBinding(Unknown Source)
	at javax.swing.JComponent.processKeyBindings(Unknown Source)
	at javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

Reported by: patrickthijssen

**Comment by rensink** [comment]
- **status**: open --> accepted
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
Fixed in the HEAD (as of revision 6273)

Original comment by: rensink
