### ISSUE TITLE
NullPointerException while loading rule system

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#514]
Stack trace upon loading the attached grammar in version 6.6.1:

Exception in GROOVE java.lang.NullPointerException: Cannot invoke "nl.utwente.groove.grammar.Rule.getQualName()" because "rule" is null
	at nl.utwente.groove.control.parse.Namespace.addRule(Namespace.java:86)
	at nl.utwente.groove.control.CtrlLoader.<init>(CtrlLoader.java:63)
	at nl.utwente.groove.grammar.model.CompositeControlModel.getLoader(CompositeControlModel.java:115)
	at nl.utwente.groove.grammar.model.CompositeControlModel.compute(CompositeControlModel.java:88)
	at nl.utwente.groove.grammar.model.CompositeControlModel.compute(CompositeControlModel.java:1)
	at nl.utwente.groove.grammar.model.ResourceModel.synchronise(ResourceModel.java:136)
	at nl.utwente.groove.grammar.model.CompositeControlModel.getRecipes(CompositeControlModel.java:126)
	at nl.utwente.groove.grammar.model.RuleModel.getRecipes(RuleModel.java:148)
	at nl.utwente.groove.grammar.model.RuleModel.hasRecipes(RuleModel.java:153)
	at nl.utwente.groove.gui.action.EnableAction.refresh(EnableAction.java:56)
	at nl.utwente.groove.gui.action.ActionStore.refreshActions(ActionStore.java:81)
	at nl.utwente.groove.gui.action.ActionStore.update(ActionStore.java:59)
	at nl.utwente.groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1202)
	at nl.utwente.groove.gui.SimulatorModel.finish(SimulatorModel.java:1171)
	at nl.utwente.groove.gui.SimulatorModel.setDisplay(SimulatorModel.java:1099)
	at nl.utwente.groove.gui.UserSettings$2.run(UserSettings.java:138)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
	at nl.utwente.groove.gui.dialog.BugReportDialog.<init>(BugReportDialog.java:102)
	at nl.utwente.groove.Simulator$1.uncaughtException(Simulator.java:36)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:701)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:696)
	at java.desktop/java.awt.EventDispatchThread.processException(EventDispatchThread.java:222)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:214)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Reported by: rensink

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
This was already solved in the HEAD, after producing 6.6.1

Original comment by: rensink
