### ISSUE TITLE
Exception in GROOVE java.lang.NumberFormatException: Character N is neither a decimal digit number, decimal point, nor "e" notation exponential mark.

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#518]
This happens when I try to display a graph generated by a derivation in the simlulator, using version 6_6_4. Model is attached. 

Exception in GROOVE java.lang.NumberFormatException: Character N is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:586)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:471)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:900)
	at java.base/java.math.BigDecimal.valueOf(BigDecimal.java:1368)
	at nl.utwente.groove.algebra.Constant.instance(Constant.java:264)
	at nl.utwente.groove.algebra.JavaRealAlgebra.toTerm(JavaRealAlgebra.java:152)
	at nl.utwente.groove.grammar.host.ValueNode.getTerm(ValueNode.java:108)
	at nl.utwente.groove.grammar.aspect.GraphConverter.toAspectMap(GraphConverter.java:140)
	at nl.utwente.groove.gui.display.StateDisplay.getAspectMap(StateDisplay.java:747)
	at nl.utwente.groove.gui.display.StateDisplay.getAspectJModel(StateDisplay.java:481)
	at nl.utwente.groove.gui.display.StateDisplay.displayState(StateDisplay.java:434)
	at nl.utwente.groove.gui.display.StateDisplay.update(StateDisplay.java:310)
	at nl.utwente.groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1200)
	at nl.utwente.groove.gui.SimulatorModel.finish(SimulatorModel.java:1169)
	at nl.utwente.groove.gui.SimulatorModel.setState(SimulatorModel.java:627)
	at nl.utwente.groove.gui.display.LTSDisplay$MyMouseListener.mouseClicked(LTSDisplay.java:668)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4584)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Reported by: rh122

**Comment by rensink** [comment]
Interesting. The issue here seems to be that the graph contains a NaN (Not a Number) value. This is probably due to the division in the msg-rule. This can be resolved in more than one way, any preference?

1. The offending graph is not generated; i.e., a rule (in this case msg) cannot be applied if the outcome of an operation is NaN. This solution best fits the underlying attribute paradigm, but it is probably hard to debug for a user who has created such a rule and is now faced with the fact that it is not applicable, since the reason for non-applicability is not given.
2. The offending graph is generated but marked as erroneous. This would be in line with the way (e.g.) multiplicity violations are handled.
3. NaN is generated and displayed as-is, without fuss. 

Come to think of it, I believe that 1. is what happens with integer division-by-zero, so that would be my go-to solution; but 2. may still be worthwhile considering even for integer division.


Original comment by: rensink

**Comment by rensink** [comment]
In terms of the algebra, division by 0 is undefined, so formally it would be correct to not have an attribute link in that case, as there is nothing to link to. There is no constraint as such saying that all attributes should have values, so this would be a correct graph, althogh it may also be hard to spot. I suppose the longer term solution is to have constraints saying that the atribute should be defined.

Original comment by: rh122

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
You can in fact specify that the attribute should be defined by giving it a multiplicity of 1.

I've resolved the bug by applying solution 1 above, see release 6.6.5

Original comment by: rensink
