### ISSUE TITLE
Addition of edge crashes GROOVE

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#523]
Add a Person node with an outgoing edge to the start graph of the enclosed system causes a crash with the enclosed stack trace:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "nl.utwente.groove.grammar.model.GraphBasedModel$TypeModelMap.getFactory()" because the return value of "nl.utwente.groove.grammar.model.HostModel.getTypeMap()" is null
	at nl.utwente.groove/nl.utwente.groove.gui.jgraph.AspectJModel$2.computeValue(AspectJModel.java:110)
	at nl.utwente.groove/nl.utwente.groove.gui.jgraph.AspectJModel$2.computeValue(AspectJModel.java:1)
	at nl.utwente.groove/nl.utwente.groove.util.ChangeCount$Derived.getValue(ChangeCount.java:117)
	at nl.utwente.groove/nl.utwente.groove.gui.jgraph.AspectJModel.getTypeGraph(AspectJModel.java:306)
	at nl.utwente.groove/nl.utwente.groove.gui.tree.TypeTree.getTypeGraph(TypeTree.java:182)
	at nl.utwente.groove/nl.utwente.groove.gui.tree.TypeTree.clearFilter(TypeTree.java:194)
	at nl.utwente.groove/nl.utwente.groove.gui.tree.LabelTree.updateModel(LabelTree.java:230)
	at nl.utwente.groove/nl.utwente.groove.gui.tree.TypeTree$1.propertyChange(TypeTree.java:94)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at nl.utwente.groove/nl.utwente.groove.util.Observable.notifyObservers(Observable.java:68)
	at nl.utwente.groove/nl.utwente.groove.util.Observable.notifyObservers(Observable.java:61)
	at nl.utwente.groove/nl.utwente.groove.util.ChangeCount.increase(ChangeCount.java:34)
	at nl.utwente.groove/nl.utwente.groove.gui.jgraph.AspectJModel.setGraphModified(AspectJModel.java:447)
	at nl.utwente.groove/nl.utwente.groove.gui.jgraph.AspectJModel.setGraph(AspectJModel.java:272)
	at nl.utwente.groove/nl.utwente.groove.gui.jgraph.AspectJModel.syncGraph(AspectJModel.java:258)
	at nl.utwente.groove/nl.utwente.groove.gui.jgraph.AspectJModel.fireGraphChanged(AspectJModel.java:480)
	at jgraph@5.13.0.0/org.jgraph.graph.DefaultGraphModel$GraphModelEdit.execute(Unknown Source)
	at jgraph@5.13.0.0/org.jgraph.graph.DefaultGraphModel.insert(Unknown Source)
	at nl.utwente.groove/nl.utwente.groove.gui.jgraph.AspectJModel.insert(AspectJModel.java:402)
	at nl.utwente.groove/nl.utwente.groove.gui.jgraph.AspectJGraph.addEdge(AspectJGraph.java:350)
	at nl.utwente.groove/nl.utwente.groove.gui.jgraph.JGraphUI$MouseHandler.finishEdgeAdding(JGraphUI.java:560)
	at nl.utwente.groove/nl.utwente.groove.gui.jgraph.JGraphUI$MouseHandler.mouseClicked(JGraphUI.java:198)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4584)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Reported by: rensink

**Comment by rensink** [comment]
- **status**: open --> closed-fixed
- **assigned_to**: Arend Rensink


Original comment by: rensink

**Comment by rensink** [comment]
This was essentially a consequence of the way a previous bug was solved, having to do with the failure to update node sizes after a local edit causes errors (and hence label updates) in the remainder of the graph

Original comment by: rensink
