### ISSUE TITLE
exception when switching back to rule view

### ISSUE THREAD

**Issue by rh122** [nl-utwente-groove/code#768]
I’m facing a persistent problem, see below, which occurs when after exploring some matches I switch back to the rule view of mk-I. 

[poly-simplex.gps.zip](https://github.com/nl-utwente-groove/code/files/14835918/poly-simplex.gps.zip)

This is an exercise in pentominoes, a suite of combinarorial problems a bit like Tetris.

https://www.cimt.org.uk/resources/puzzles/pentoes/pentoint.htm#:~:text=So%20there%20are%20monominoes%20(1,6%20squares)%20and%20so%20on.

Exception in GROOVE java.lang.NullPointerException: Cannot invoke "javax.accessibility.AccessibleContext.getAccessibleRole()" because "nvAC" is null
	at java.desktop/sun.lwawt.macosx.CAccessibility.propertyChange(CAccessibility.java:114)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1489)
	at java.desktop/java.awt.KeyboardFocusManager.setGlobalFocusOwner(KeyboardFocusManager.java:580)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:651)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by rensink** [comment]
I'm afraid I can't do anything with this. It seems to be a MacOS-related bug; I've found a few similar reports on the internet, but with no hints on how to resolve it. I can't reproduce the behaviour myself and the stack trace at no point refers to any GROOVE-code so I can't even insert a breakpoint.

I've had reports of similar (accessibility-related, MacOS-based) bugs before. At one point a colleague of mine who owns a Mac was kind enough to put some time into it. Unfortunately I can't find back his conclusions any more; off the top of my head, he came up with a very strange issue having to do with voice commands being enabled.

I guess you're using the OpenJDK VM? If not, then that may be the best thing to try. Otherwise, the only reliable way to run GROOVE on a Mac seems to be to run it in a Windows emulator...

**Comment by rh122** [comment]
Ok, thanks. I disabled the permissions there for a few apps that I didn’t really use.

Bests
Reiko



On 11/04/2024, 14:57, "Arend Rensink" ***@***.***> wrote:

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

***CAUTION:*** This email was sent from an EXTERNAL source. Think before clicking links or opening attachments.

I've gotten some help with this, and may have a solution after all. Here's what another Mac user reported:

it seems the issue can be resolved by disabling certain conflicting applications in

System Preferences > Security & Privacy > Accessibility

in my case, after a couple of attempts, it seems that the problem was caused by Magnet,
an application for automatic resizing and positioning windows on the screen.

https://magnet.crowdcafe.com/

After disabling its privileges, I am now able to click, drag, etc in the edit panels of Simulator.

I've also added a page to the web site about this: see https://groove.cs.utwente.nl/mac.html
