### ISSUE TITLE
Changing an edge to rem: throws exception

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#769]
Adding a rem:-prefix to an edge in a rem:-node (because without that prefix an error was reported due to the presence of a colon) threw the error reproduced below.

```
Exception in GROOVE java.lang.NullPointerException: Cannot read field "modelNodes" because "ascendingLevel" is null
	at nl.utwente.groove.grammar.model.RuleModel$Level1.addNodeToParents(RuleModel.java:1206)
	at nl.utwente.groove.grammar.model.RuleModel$Level1.addEdge(RuleModel.java:1169)
	at nl.utwente.groove.grammar.model.RuleModel$LevelTree.buildLevels1(RuleModel.java:910)
	at nl.utwente.groove.grammar.model.RuleModel$LevelTree.<init>(RuleModel.java:724)
	at nl.utwente.groove.grammar.model.RuleModel.compute(RuleModel.java:262)
	at nl.utwente.groove.grammar.model.RuleModel.compute(RuleModel.java:125)
	at nl.utwente.groove.grammar.model.ResourceModel.synchronise(ResourceModel.java:136)
	at nl.utwente.groove.grammar.model.ResourceModel.getErrors(ResourceModel.java:224)
	at nl.utwente.groove.gui.jgraph.AspectJModel.loadViewErrors(AspectJModel.java:266)
	at nl.utwente.groove.gui.jgraph.AspectJModel$3.propertyChange(AspectJModel.java:103)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at nl.utwente.groove.util.Observable.notifyObservers(Observable.java:68)
	at nl.utwente.groove.util.Observable.notifyObservers(Observable.java:61)
	at nl.utwente.groove.util.ChangeCount.increase(ChangeCount.java:34)
	at nl.utwente.groove.gui.jgraph.AspectJModel.setGraphModified(AspectJModel.java:427)
	at nl.utwente.groove.gui.jgraph.AspectJModel.setGraph(AspectJModel.java:252)
	at nl.utwente.groove.gui.jgraph.AspectJModel.syncGraph(AspectJModel.java:242)
	at nl.utwente.groove.gui.jgraph.AspectJModel.fireGraphChanged(AspectJModel.java:460)
	at org.jgraph.graph.DefaultGraphModel$GraphModelEdit.execute(Unknown Source)
	at org.jgraph.graph.DefaultGraphModel.edit(Unknown Source)
	at org.jgraph.graph.DefaultGraphModel.edit(Unknown Source)
	at org.jgraph.graph.GraphLayoutCache.edit(Unknown Source)
	at org.jgraph.graph.GraphLayoutCache.valueForCellChanged(Unknown Source)
	at org.jgraph.plaf.basic.BasicGraphUI.completeEditing(Unknown Source)
	at org.jgraph.plaf.basic.BasicGraphUI$CellEditorHandler.editingStopped(Unknown Source)
	at java.desktop/javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:152)
	at java.desktop/javax.swing.AbstractCellEditor.stopCellEditing(AbstractCellEditor.java:96)
	at nl.utwente.groove.gui.jgraph.MultiLinedEditor$RealCellEditor$StopEditAction.actionPerformed(MultiLinedEditor.java:314)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2947)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2995)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2909)
	at java.desktop/java.awt.Component.processEvent(Component.java:6403)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1952)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:883)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1150)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:848)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
````

**Comment by rensink** [comment]
The casue of the bug was a rem:-edge to a quantifier node. Resolved by filtering out rem:-edges earlier in the process.
