### ISSUE TITLE
Crash while editing in Simulator 

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#773]
The circumstances under which this occured are not clear. Here's a stack trace:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "nl.utwente.groove.grammar.model.NamedResourceModel.isActive()" because the return value of "nl.utwente.groove.gui.display.ResourceDisplay.getResource(nl.utwente.groove.grammar.QualName)" is null
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.display.ResourceDisplay.getLabelText(ResourceDisplay.java:650)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.display.ResourceTab.updateDirty(ResourceTab.java:320)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.display.TextTab$1.stateChanged(TextTab.java:266)
	at java.desktop/javax.swing.AbstractButton.fireStateChanged(AbstractButton.java:1865)
	at java.desktop/javax.swing.AbstractButton$Handler.stateChanged(AbstractButton.java:2305)
	at java.desktop/javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:352)
	at java.desktop/javax.swing.DefaultButtonModel.setEnabled(DefaultButtonModel.java:211)
	at java.desktop/javax.swing.AbstractButton.setEnabled(AbstractButton.java:2050)
	at java.desktop/javax.swing.AbstractAction.setEnabledFromAction(AbstractAction.java:106)
	at java.desktop/javax.swing.AbstractButton.actionPropertyChanged(AbstractButton.java:1187)
	at java.desktop/javax.swing.AbstractButton$ButtonActionPropertyChangeListener.actionPropertyChanged(AbstractButton.java:1334)
	at java.desktop/javax.swing.AbstractButton$ButtonActionPropertyChangeListener.actionPropertyChanged(AbstractButton.java:1322)
	at java.desktop/javax.swing.ActionPropertyChangeListener.propertyChange(ActionPropertyChangeListener.java:94)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:93)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/javax.swing.AbstractAction.firePropertyChange(AbstractAction.java:284)
	at java.desktop/javax.swing.AbstractAction.setEnabled(AbstractAction.java:240)
	at rsyntaxtextarea@1.5.2/org.fife.ui.rtextarea.RUndoManager.updateActions(RUndoManager.java:206)
	at rsyntaxtextarea@1.5.2/org.fife.ui.rtextarea.RUndoManager.undoableEditHappened(RUndoManager.java:161)
	at java.desktop/javax.swing.text.AbstractDocument.fireUndoableEditUpdate(AbstractDocument.java:316)
	at java.desktop/javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:655)
	at java.desktop/javax.swing.text.AbstractDocument.remove(AbstractDocument.java:619)
	at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:695)
	at java.desktop/javax.swing.text.JTextComponent.setText(JTextComponent.java:1729)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.display.TextTab$TextArea.setProgram(TextTab.java:303)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.display.TextTab.updateGrammar(TextTab.java:159)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.display.ResourceDisplay.updateGrammar(ResourceDisplay.java:464)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.display.ResourceDisplay.update(ResourceDisplay.java:444)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.display.ControlDisplay.update(ControlDisplay.java:150)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.SimulatorModel.fireUpdate(SimulatorModel.java:1316)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.SimulatorModel.finish(SimulatorModel.java:1285)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.SimulatorModel.doDelete(SimulatorModel.java:104)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.action.DeleteAction.execute(DeleteAction.java:51)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.action.SimulatorAction.actionPerformed(SimulatorAction.java:224)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "nl.utwente.groove.grammar.model.NamedResourceModel.isActive()" because the return value of "nl.utwente.groove.gui.display.ResourceDisplay.getResource(nl.utwente.groove.grammar.QualName)" is null
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.display.ResourceDisplay.getLabelText(ResourceDisplay.java:650)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.tree.ResourceTreeNode.getText(ResourceTreeNode.java:78)
	at nl.utwente.groove@6.8.3/nl.utwente.groove.gui.tree.DisplayTreeCellRenderer.getTreeCellRendererComponent(DisplayTreeCellRenderer.java:59)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:3223)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache.getBounds(FixedHeightLayoutCache.java:555)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache.getBounds(FixedHeightLayoutCache.java:201)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.getPathBounds(BasicTreeUI.java:680)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.getPathBounds(BasicTreeUI.java:673)
	at java.desktop/javax.swing.JTree.getPathBounds(JTree.java:2194)
	at java.desktop/javax.swing.JTree.getPathForLocation(JTree.java:2350)
	at java.desktop/javax.swing.JTree.getRowForLocation(JTree.java:2372)
	at java.desktop/javax.swing.JTree.getToolTipText(JTree.java:1608)
	at java.desktop/javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:693)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by rensink** [comment]
Without ability to reproduce, just implemented a minimal change to avoid this particular NPE
