### ISSUE TITLE
Crash upon deleting rules (due to GxlIO error)

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#798]
A crash with stack trace below occurs when trying to delete the rules `environment-fired` and  `react` from the following rule system:

[prune-occurrence-graph-rs.gps.zip](https://github.com/user-attachments/files/16388298/prune-occurrence-graph-rs.gps.zip)

```Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Unreachable location
	at nl.utwente.groove/nl.utwente.groove.util.Exceptions.<clinit>(Exceptions.java:28)
	at nl.utwente.groove/nl.utwente.groove.util.parse.Parser$AParser.lambda$0(Parser.java:274)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at nl.utwente.groove/nl.utwente.groove.util.parse.Parser$AParser.getDefaultValue(Parser.java:273)
	at nl.utwente.groove/nl.utwente.groove.util.parse.Parser.isDefault(Parser.java:149)
	at nl.utwente.groove/nl.utwente.groove.util.parse.Parser$EnumParser.createDescription(Parser.java:645)
	at nl.utwente.groove/nl.utwente.groove.util.parse.Parser$AParser.getDescription(Parser.java:245)
	at nl.utwente.groove/nl.utwente.groove.util.parse.Parser$OptionalParser.<init>(Parser.java:679)
	at nl.utwente.groove/nl.utwente.groove.graph.GraphProperties$Key.parser(GraphProperties.java:215)
	at nl.utwente.groove/nl.utwente.groove.util.Properties.setProperty(Properties.java:270)
	at nl.utwente.groove/nl.utwente.groove.io.graph.GxlIO.gxlToGraph(GxlIO.java:489)
	at nl.utwente.groove/nl.utwente.groove.io.graph.GxlIO.loadGraph(GxlIO.java:356)
	at nl.utwente.groove/nl.utwente.groove.io.graph.GxlIO.loadGraph(GxlIO.java:321)
	at nl.utwente.groove/nl.utwente.groove.io.store.SystemStore.loadGraphs(SystemStore.java:725)
	at nl.utwente.groove/nl.utwente.groove.io.store.SystemStore.doReload(SystemStore.java:553)
	at nl.utwente.groove/nl.utwente.groove.io.store.SystemStore.reload(SystemStore.java:537)
	at nl.utwente.groove/nl.utwente.groove.gui.action.LoadGrammarAction.load(LoadGrammarAction.java:90)
	at nl.utwente.groove/nl.utwente.groove.gui.action.LoadGrammarFromHistoryAction.execute(LoadGrammarFromHistoryAction.java:44)
	at nl.utwente.groove/nl.utwente.groove.gui.action.SimulatorAction.actionPerformed(SimulatorAction.java:224)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by rensink** [comment]
The problem was elsewhere, but it seems to be resolved
